//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by step_plugin.popup_mft_msg_step.rc
//
#define IDD_PLAN_STEP_EDIT_POPUP_MFT_MESSAGE_DLG 26200
#define IDC_THIRD_OPTION_STEP           26210
#define IDC_DECISION_MESSAGE            26211
#define IDC_THIRD_PICK_STEP_BUTTON      26212
#define IDC_POPUP_PICK_STEP_BUTTON      26213
#define IDC_POPUP_SUCCESS_STEP          26214
#define IDC_POPUP_TIMESPAN_PICKER       26215
#define IDC_OPERATOR_PROFILE_COMBO      26216
#define IDC_MESSAGEBOX_STYLE_COMBO      26217
#define IDC_FIRST_BUTTON_STATIC         26218
#define IDC_SECOND_BUTTON_STATIC        26219
#define IDC_THIRD_BUTTON_STATIC         26220
#define IDC_FIRST_PICK_STEP_BUTTON      26221
#define IDC_SECOND_PICK_STEP_BUTTON     26222
#define IDC_FIRST_OPTION_STEP           26223
#define IDC_SECOND_OPTION_STEP          26224
#define IDS_POPUP_STEP_PARAMETER_DECISION_MESSAGE 26230
#define IDS_POPUP_STEP_PARAMETER_YES_STEP         26231
#define IDS_POPUP_STEP_PARAMETER_NO_STEP          26232
#define IDS_POPUP_STEP_PARAMETER_PENDING_STEP     26233
#define IDS_POPUP_STEP_PARAMETER_ABORT_STEP       26234
#define IDS_POPUP_STEP_PARAMETER_IGNORE_STEP      26235
#define IDS_POPUP_STEP_PARAMETER_RETRY_STEP       26236
#define IDS_POPUP_STEP_PARAMETER_OK_STEP          26237
#define IDS_POPUP_STEP_PARAMETER_CANCEL_STEP      26238
#define IDS_POPUP_STEP_PARAMETER_MESSAGEBOX_STYLE 26239
#define IDS_POPUP_STEP_PARAMETER_TIME_SPAN        26240
#define IDS_POPUP_STEP_PARAMETER_PROFILE_NAME     26241

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        27000
#define _APS_NEXT_COMMAND_VALUE         27001
#define _APS_NEXT_CONTROL_VALUE         27002
#define _APS_NEXT_SYMED_VALUE           27003
#endif
#endif
