#ifndef PA_TABLE_CONSTS__INCLUDED_
#define PA_TABLE_CONSTS__INCLUDED_

namespace TA_Base_Core
{
// Common column names
const char* const KEY_COL = "PKEY";
const char* const LOCATION_KEY_COL = "LOCATION_KEY";

const char* const DATE_MODIFIED_COL = "DATE_MODIFIED";
const char* const DATE_CREATED_COL = "DATE_CREATED";
// Table PA_SCHEDULE_BROADCAST
const char* const PA_SCHEDULE_BROADCAST_TABLE = "PA_SCHEDULE_BROADCAST";

const char* const PA_SCHEDULE_BROADCAST_SCHEDULE_NAME_COL = "SCHEDULE_NAME";
const char* const PA_SCHEDULE_BROADCAST_START_TIME_COL = "START_TIME";
const char* const PA_SCHEDULE_BROADCAST_END_TIME_COL = "END_TIME";
const char* const PA_SCHEDULE_BROADCAST_INTERVAL_TYPE_COL = "INTERVAL_TYPE";
const char* const PA_SCHEDULE_BROADCAST_IS_ENABLE_COL = "IS_ENABLE";
const char* const PA_SCHEDULE_BROADCAST_AUTO_DEL_COL = "AUTO_DEL";
const char* const PA_SCHEDULE_BROADCAST_CYCLIC_TIMES_COL = "CYCLIC_TIMES";
const char* const PA_SCHEDULE_BROADCAST_PRIORY_GROUP_COL = "PRIORY_GROUP";
const char* const PA_SCHEDULE_BROADCAST_SOURCE_TYPE_COL = "SOURCE_TYPE";
const char* const PA_SCHEDULE_BROADCAST_STATUS_COL = "STATUS";

const char* const PA_SCHEDULE_BROADCAST_SCHEDULE_ID_COL = "SCHEDULE_ID";
const char* const PA_SCHEDULE_BROADCAST_INTERVAL_TIME_COL = "INTERVAL_TIME";
const char* const PA_SCHEDULE_BROADCAST_CHIME_COL = "CHIME";
const char* const PA_SCHEDULE_BROADCAST_SUN_COL = "SUN";
const char* const PA_SCHEDULE_BROADCAST_MON_COL = "MON";
const char* const PA_SCHEDULE_BROADCAST_TUE_COL = "TUE";
const char* const PA_SCHEDULE_BROADCAST_WED_COL = "WED";
const char* const PA_SCHEDULE_BROADCAST_THU_COL = "THU";
const char* const PA_SCHEDULE_BROADCAST_FRI_COL = "FRI";
const char* const PA_SCHEDULE_BROADCAST_SAT_COL = "SAT";

const char* const PA_SCHEDULE_BROADCAST_SEQUENCE_COUNTER = "PA_SCHEDULE_BROADCAST_SEQ";

const char* const ONCE_SCHEDULE_INTERVAL_TYPE = "O";
const char* const EVERYDAY_SCHEDULE_INTERVAL_TYPE = "D";
const char* const EVERYWEEK_SCHEDULE_INTERVAL_TYPE = "W";
const char* const EVERYMONTH_SCHEDULE_INTERVAL_TYPE = "M";
const char* const EVERYYEAR_SCHEDULE_INTERVAL_TYPE = "Y";

const char* const DVA_MSG_SOURCE_TYPE = "D";
const char* const ADHOC_MSG_SOURCE_TYPE = "A";

const char* const SCHEDULE_STATUS_SUCCESSFUL = "S";
const char* const SCHEDULE_STATUS_FAILED = "F";
const char* const SCHEDULE_STATUS_WAITING = "W";

const char* const INVALID_STRING_VALUE = "X";

// Table PA_SCHEDULE_BROADCAST_ZONES
const char* const PA_SCHEDULE_BROADCAST_ZONES_TABLE = "PA_SCHEDULE_BROADCAST_ZONES";

const char* const PA_SCHEDULE_BROADCAST_ZONES_SCHEDULE_BROADCAST_KEY_COL = "SCHEDULE_BROADCAST_KEY";
const char* const PA_SCHEDULE_BROADCAST_ZONES_ZONE_KEY_COL = "ZONE_KEY";

// Table PA_SCHEDULE_BROADCAST_MSGS
const char* const PA_SCHEDULE_BROADCAST_MSGS_TABLE = "PA_SCHEDULE_BROADCAST_MSGS";

const char* const PA_SCHEDULE_BROADCAST_MSGS_SCHEDULE_BROADCAST_KEY_COL = "SCHEDULE_BROADCAST_KEY";
const char* const PA_SCHEDULE_BROADCAST_MSGS_MSG_KEY_COL = "MSG_KEY";

}

#endif
