//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PAManager.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DLG_PA_MAIN_WND             102
#define IDD_PROPPAGE_EMERGENCY          106
#define IDD_PROPPAGE_NORMAL             107
#define IDD_PROPPAGE_OTHER              108
#define IDR_MAINFRAME                   128
#define IDB_UNLOCKMODE                  129
#define IDB_LOCKMODE                    130
#define IDD_DLG_BROADCAST_DES_EDIT      131
#define IDD_DLG_GROUP_EDIT              132
#define IDD_DLG_SCHEDULE_BROADCAST      133
#define IDR_MENU_DVA_MSG_SHORTCUT_CONFIG 135
#define IDD_DLG_PROGRESS_STATUS         136
#define IDB_UNKNOW                      137
#define IDD_DLG_SCHEDULE_IN_DAY         138
#define IDC_GWX_ZONESAREA               1000
#define IDC_BROADCASTINFO_TABMARKER     1001
#define IDC_CHECK_CYCLE                 1002
#define IDC_BTN_BROADCAST_A             1003
#define IDC_BTN_BROADCAST_B             1004
#define IDC_BTN_BROADCAST_C             1005
#define IDC_BTN_BROADCAST_D             1006
#define IDC_BTN_BROADCAST_E             1007
#define IDC_BTN_BROADCAST_F             1008
#define IDC_BTN_BROADCAST_G             1009
#define IDC_BTN_BROADCAST_H             1010
#define IDC_BTN_BROADCAST_I             1011
#define IDC_BTN_BROADCAST_J             1012
#define IDC_BTN_BROADCAST_K             1013
#define IDC_BTN_BROADCAST_L             1014
#define IDC_BTN_BROADCAST_M             1015
#define IDC_BTN_BROADCAST_N             1016
#define IDC_BTN_BROADCAST_O             1017
#define IDC_BTN_BROADCAST_P             1018
#define IDC_BTN_BROADCAST_Q             1019
#define IDC_BTN_BROADCAST_R             1020
#define IDC_BTN_BROADCAST_S             1021
#define IDC_BTN_BROADCAST_T             1022
#define IDC_BTN_BROADCAST_U             1100
#define IDC_BTN_BROADCAST_V             1101
#define IDC_BTN_BROADCAST_W             1102
#define IDC_BTN_BROADCAST_X             1103
#define IDC_BTN_BROADCAST_Y             1104
#define IDC_BTN_BROADCAST_Z             1105
#define IDC_ZONE_AREA_MARKER            1023
#define IDC_BTN_SCHEDULE                1024
#define IDC_BTN_GROUP_SAVE              1025
#define IDC_BTN_GROUP_DELETE            1026
#define IDC_COMBO_GROUP                 1029
#define IDC_EDIT_CUR_BROADCAST_NAME     1030
#define IDC_BTN_BROADCAST_START         1031
#define IDC_BTN_LIVE_BROADCAST          1032
#define IDC_BTN_BROADCAST_STOP          1033
#define IDC_BTN_HELP                    1034
#define IDC_TIME_CYCLE_START            1035
#define IDC_TIME_CYCLE_END              1036
#define IDC_EDIT_CYCLE_TIMES            1037
#define IDC_TIME_START_IN_DAY           1038
#define IDC_EDIT_SEARCH_KEYWORD_O       1040
#define IDC_BTN_LIST_ALL_O              1042
#define IDC_LIST_EMERGENCY_BROADCAST    1043
#define IDC_EDIT_BROADCAST_DES_O        1044
#define IDC_BTN_EMERGENCY_DES_EDIT      1045
#define IDC_EDIT_SEARCH_KEYWORD_N       1046
#define IDC_BTN_LIST_ALL_N              1048
#define IDC_EDIT_BROADCAST_DES_N        1049
#define IDC_BTN_NORMAL_DES_EDIT         1050
#define IDC_EDIT_BROADCAST_DES_E        1051
#define IDC_BTN_LIST_ALL_E              1053
#define IDC_EDIT_SEARCH_KEYWORD_E       1054
#define IDC_BTN_OTHER_DES_EDIT          1055
#define IDC_LIST_OTHER_BROADCAST        1056
#define IDC_LIST_NORMAL_BROADCAST       1057
#define IDC_EDIT_BROADCAST_DES          1058
#define IDC_EDIT_GROUP_NAME             1060
#define IDC_LIST_SELED_ZONES            1061
#define IDC_BTN_CONFIRM                 1064
#define IDC_BTN_CANCEL                  1065
#define IDC_EDIT_SCHEDULE_NAME          1066
#define IDC_COMBO_BROADCAST_FREQUENCY   1067
#define IDC_COMBO_WEEK_DETAIL           1068
#define IDC_CHECK_AUTO_DELETE           1069
#define IDC_LIST_BROADCAST_SCHEDULE     1070
#define IDC_EDIT_BROADCAST_MSG          1071
#define IDC_EDIT_BROADCAST_ZONES        1072
#define IDC_BTN_DELETE_SCHEDULE         1073
#define IDC_BTN_ENABLE_SCHEDULE         1074
#define IDC_COMBO_MONTH_DETAIL          1075
#define IDC_BTN_DISABLE_SCHEDULE        1075
#define IDC_CHECK_DVA_BROADCAST         1076
#define IDC_CHECK_LIVE_BROADCAST        1077
#define IDC_BTN_TASTE_DVA               1078
#define IDC_BTN_MONITOR_START           1079//added by lixiaoxia
#define IDC_BTN_MONITOR_STOP            1080//added by lixiaoxia
#define IDC_BTN_EXIT                    1082
#define IDC_BTN_MODIFY_NAME             1084
#define IDC_PIC_BACKUP_STATUS           1085
#define IDC_PIC_GUI_LOCK                1085
#define IDC_STATIC_STATUS               1089
#define IDC_CHECK_SCHEDULE_IN_DAY       1090
#define IDC_BTN_DELETE_SCHEDULE_IN_DAY  1091
#define IDC_BTN_HIDE                    1092
#define IDC_LIST_SCHEDULE_ZONES         1093
#define IDC_LIST_SCHEDULE_IN_DAY        1094
#define IDC_EDIT_SCHEDULE_DVA_MSG       1095
#define IDC_EDIT_SCHEDULE_CYCLIC_TIMES  1096
#define IDC_TAB_DVA_MSG                 1097
#define IDC_BTN_SCHEDULE_MANAGER        1098
#define IDC_CHECK_BACKGROUND_MUSIC      1099
#define IDC_FREQ_USED_MESSAGE           1200
#define IDC_BACKUP_KEY                  1201
#define IDC_BROADCAST_ZONE_GROUP        1202
#define IDC_BROADCAST_ZONE              1203
#define IDC_SCHEDULED_IN_DAY            1204
#define IDC_PRERECORD_MESSAGE           1205
#define IDC_CYCLIC_BROADCAST            1206
#define IDC_BROADCAST                   1207
#define IDC_TIMETABLE_BROADCAST         1208
#define IDC_BROADCAST_CONTENT           1209
#define IDC_CYCLIC                      1210
#define IDC_TIMES                       1211
#define ID_DVA_SHORTCUT_A               32782
#define ID_DVA_SHORTCUT_B               32783
#define ID_DVA_SHORTCUT_C               32784
#define ID_DVA_SHORTCUT_D               32785
#define ID_DVA_SHORTCUT_E               32786
#define ID_DVA_SHORTCUT_F               32787
#define ID_DVA_SHORTCUT_G               32788
#define ID_DVA_SHORTCUT_H               32789
#define ID_DVA_SHORTCUT_I               32790
#define ID_DVA_SHORTCUT_J               32791
#define ID_DVA_SHORTCUT_K               32792
#define ID_DVA_SHORTCUT_L               32793
#define ID_DVA_SHORTCUT_M               32794
#define ID_DVA_SHORTCUT_N               32795
#define ID_DVA_SHORTCUT_O               32796
#define ID_DVA_SHORTCUT_P               32797
#define ID_DVA_SHORTCUT_Q               32798
#define ID_DVA_SHORTCUT_R               32799
#define ID_DVA_SHORTCUT_S               32800
#define ID_DVA_SHORTCUT_T               32801
#define ID_DVA_SHORTCUT_U               32802
#define ID_DVA_SHORTCUT_V               32803
#define ID_DVA_SHORTCUT_W               32804
#define ID_DVA_SHORTCUT_X               32805
#define ID_DVA_SHORTCUT_Y               32806
#define ID_DVA_SHORTCUT_Z               32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
