//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RadioManager.rc
//
#define IDS_HISTORYCOLUMN_HISTORY       1
#define IDS_HISTORYCOLUMN_SOURCE        2
#define IDS_HISTORYCOLUMN_TEXT          3
#define IDCANCEL2                       3
#define IDD_RADIOMANAGER_DIALOG         102
#define IDD_RADIO_INBOX_PAGE            106
#define IDD_RADIO_SEND_TEXT_PAGE        107
#define IDR_MAINFRAME                   128
#define IDD_TEXT_MESSAGING_DLG          130
#define IDD_DIALOG1                     131
#define IDD_PATCHMANAGER_DIALOG         131
#define IDD_PATCHMANAGER_RADIO_PAGE     132
#define IDD_PATCHMANAGER_TALKGROUP_PAGE 133
#define IDD_PATCHMANAGER_DYNAMICREGROUP_PAGE 134
#define IDD_GENERIC_DIALPAD             135
#define IDD_NEW_ENTITY_DLG              136
#define IDD_CALLSTACK_PAGE              137
#define IDD_HISTORY_PAGE                138
#define IDR_TOOLBAR1                    139
#define IDD_DIRECTORY_PAGE              142
#define IDD_SELECTED_ENTITY             144
#define IDR_STOP_MONITORING             145
#define IDB_BITMAP_DRAG_IMAGE           146
#define IDB_BITMAP_INVALID              147
#define IDD_SELECTED_OPERATIONS         148
#define IDB_BITMAP_Rad                  149
#define IDB_BITMAP_TG                   150
#define IDB_BITMAP_AG                   151
#define IDB_BITMAP_PG                   152
#define IDB_BITMAP_DG                   153
#define IDB_BITMAP_MS                   154
#define IDB_BITMAP_SW                   155
#define IDB_BITMAP_Mu_SW                156
#define IDD_RADIOSTATUS_PAGE            159
#define IDR_MENU1                       162
#define IDR_MENU2                       163
#define IDB_DRAG_RADIO                  168
#define IDD_DEBUG                       169
#define IDB_BITMAP_DIAL                 170
#define IDD_RADIO_INITIALISE            171
#define IDD_CALLFORWARDING_PAGE1        172
#define IDD_CALLFORWARDING_PAGE         172
#define IDD_SUBS_MONITORING_PAGE        173
#define IDC_MSG_HISTORY                 1000
#define IDC_MSG_TEXT                    1001
#define IDC_BUTTON1                     1003
#define IDC_EPAX_DIAL                   1003
#define IDC_DELETE_BTN                  1003
#define IDC_CALL_BTN                    1003
#define IDC_CLEAR                       1003
#define IDC_APPLY                       1003
#define IDC_MONITORING_BTN              1003
#define IDC_BUTTON2                     1004
#define IDC_EPAX_END_CALL               1004
#define IDC_EDIT_BTN                    1004
#define IDC_ANSWER_BTN                  1004
#define IDC_DIALPAD_BTN                 1004
#define IDC_FUTURE                      1004
#define IDC_LIST1                       1005
#define IDC_MSG_SELECTION               1005
#define IDC_DLTS_DIAL                   1005
#define IDC_BUTTON3                     1005
#define IDC_HISTORY_LIST                1005
#define IDC_DIRECTORY_LIST              1005
#define IDC_ENDCALL_BTN                 1005
#define IDC_LIST                        1005
#define IDC_EMERGENCY_BTN               1005
#define IDC_REFRESHINBOX                1005
#define IDC_ADD                         1006
#define IDC_DLTS_END_CALL               1006
#define IDC_SAVE_BTN                    1006
#define IDC_SENDTEXT_BTN                1006
#define IDC_INBOX_BTN                   1006
#define IDC_REMOVE                      1007
#define IDC_PATCH_BTN                   1007
#define IDC_CANCEL_BTN                  1007
#define IDC_NEW_ENTITY_BTN              1007
#define IDC_SAVE                        1008
#define IDC_CLOSE_BTN                   1008
#define IDC_AMBIENCE_BTN                1008
#define IDC_LOCATE_SPEAKER_BTN          1008
#define IDC_DELETE_MEMBER_BTN           1008
#define IDC_CANCEL                      1009
#define IDC_CONNECT_BTN                 1009
#define IDC_EDIT1                       1010
#define IDC_TEXT_EDIT                   1010
#define IDC_DESCRIPTION                 1010
#define IDC_FILTER                      1010
#define IDC_SPEAKER_BTN                 1010
#define IDC_AFFILIATED_EDIT             1010
#define IDC_SEND                        1011
#define IDC_RELEASE_BTN                 1011
#define IDC_AFFILIATED_EDIT2            1011
#define IDC_SEL_TG_EDIT                 1011
#define IDC_CLOSE                       1012
#define IDC_ID                          1012
#define IDC_AFFILIATED_EDIT3            1012
#define IDC_ADHOC                       1013
#define IDC_MONITORING_TEXT             1013
#define IDC_PREDEFINED                  1014
#define IDC_EPAX_DESCRIPTION            1014
#define IDC_DG_TALKGROUP                1014
#define IDC_EPAX_NUMBER                 1015
#define IDC_EPAX_DIALPAD                1016
#define IDC_DLTS_DESCRIPTION            1017
#define IDC_DLTS_NUMBER                 1018
#define IDC_PATCHMANAGER_RADIO_CALL     1018
#define IDC_DLTS_DIALPAD                1019
#define IDC_PATCHMANAGER_RADIO_RELEASE  1019
#define IDC_PATCHMANAGER_RADIO_DIALPAD  1020
#define IDC_MARKER                      1021
#define IDC_DIALEDNUM_CB                1023
#define IDC_KEYPAD_0                    1024
#define IDC_KEYPAD_1                    1025
#define IDC_KEYPAD_2                    1026
#define IDC_KEYPAD_3                    1027
#define IDC_KEYPAD_4                    1028
#define IDC_ENTITY_TYPE_CB              1028
#define IDC_KEYPAD_5                    1029
#define IDC_CALLSTACK_LIST              1029
#define IDC_KEYPAD_6                    1030
#define IDC_PROPSHEET_HOLDER            1030
#define IDC_KEYPAD_7                    1031
#define IDC_ENTITY_TAB                  1031
#define IDC_BUTTON19                    1031
#define IDC_KEYPAD_8                    1032
#define IDC_ENTITY_DESCRIPTION          1032
#define IDC_KEYPAD_9                    1033
#define IDC_ENTITY_NUMBER               1033
#define IDC_KEYPAD_ST                   1034
#define IDC_KEYPAD_PND                  1035
#define IDC_KEYPAD_BACKSP               1036
#define IDC_TAB1                        1039
#define IDC_DIRECTORY_PANEL_HOLDER      1042
#define IDC_TYPE                        1043
#define IDC_STATIC_TEXT                 1045
#define IDC_DG_TEXT                     1046
#define IDC_SELECTED_ENTITY_STATIC      1047
#define IDC_ENTITY_DETAILS              1049
#define IDC_DETAILS_HOLDER              1050
#define IDC_STATIC_TYPE                 1051
#define IDC_STATIC_DESC                 1052
#define IDC_ENTITY_OPERATIONS           1052
#define IDC_STATIC_ID                   1053
#define IDC_OPERATIONS_HOLDER           1053
#define IDC_STATIC_BLANK                1054
#define IDC_VOLUME_SLIDER               1056
#define IDC_STATIC_VOLUME               1057
#define IDC_CHARS_USED                  1058
#define IDC_CHARS_AVAILABLE             1059
#define IDC_DUMMY_NEW_PATCH             1060
#define IDC_DUMMY_SEND_TEXT             1061
#define IDC_CHAR_SET_TEXT               1061
#define IDC_DUMMY_ORIGINAL_PATCH        1062
#define ID_GENERIC_DIALPAD_OK           1067
#define IDC_INITIALISE_MSG              1068
#define IDC_MAX                         1069
#define IDC_MIN                         1070
#define IDC_FILTER_ID                   1072
#define IDC_STATIC_MONITOR              1074
#define IDC_CUSTOM1                     1075
#define IDC_STATIC_MONITOR2             1075
#define IDC_STATIC_MONITOR3             1076
#define IDC_CHECK1                      1077
#define IDC_EMERGENCY_CHECK             1077
#define IDC_EMERGENCY_STATIC            1078
#define IDC_RADIO_BUTTON_GROUP          1079
#define IDC_RADIO1                      1080
#define IDC_RADIO2                      1081
#define IDC_RADIO3                      1082
#define IDC_EXTENSION                   1083
#define IDC_COMBO1                      1084
#define IDC_COMBO2                      1085
#define IDC_AFFILIATED_STATIC           1085
#define IDC_SEL_TG_STATIC               1086
#define IDC_RESULT_STATIC               1087
#define ID_DIALPAD_TB                   32776
#define ID_INBOX_TB                     32780
#define ID_NEW_ENTITY_TB                32781
#define IDS_COL_HEADER_DESC             32786
#define IDS_COL_HEADER_TYPE             32787
#define IDM_STOP_MONITORING             32787
#define IDS_COL_HEADER_ID               32788
#define IDS_COL_HEADER_STATUS           32789
#define IDS_COL_HEADER_SOURCE           32790
#define IDS_COL_HEADER_TIME             32791
#define IDS_COL_HEADER_ACTION           32792
#define IDS_RR_NIL                      32793
#define IDS_RR_RADIO                    32794
#define ID_EMERGENCYMODE_TB             32794
#define IDS_RR_TALKGROUP                32795
#define IDS_RR_ANNGROUP                 32796
#define ID_DELETE_MENU                  32796
#define IDS_RR_PATCHGROUP               32797
#define ID_STOP_MONITOR_MENU            32797
#define ID_ACKNOWLEDGE_EMERGENCY_MENU   32798
#define IDS_RR_DYNGROUP                 32798
#define ID_KNOCKDOWN_EMERGENCY_MENU     32799
#define IDS_RR_MSELECT                  32799
#define ID_START_EMERGENCY_MENU         32800
#define IDS_RR_SITE                     32800
#define IDS_RR_MSITE                    32801
#define IDS_RR_TRAIN                    32802
#define IDS_PATCH_STATUS                32803
#define IDS_STATUS_BAR_MSG_1            32804
#define IDS_STATUS_BAR_MSG_2            32805
#define IDS_STATUS_BAR_MSG_3            32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
