//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by STISManager.rc
//
#define IDD_STISMANAGER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_LED_ATTRIBUTES              129
#define IDD_PLASMA_ATTRIBUTES           130
#define IDR_MENU1                       131
#define IDD_PREDEFINED                  132
#define IDD_FREE_TEXT                   133
#define IDD_RATIS_APPROVAL              134
#define IDD_RATIS                       135
#define IDD_DISPLAY_PAGE                136
#define IDD_VERSION_PAGE                137
#define IDD_DIALOG1                     138
#define IDD_PID_GROUP_NAME              138
#define IDD_DLG_INITPROGRESS            140
#define IDC_RADIO_PREDEFINED            1000
#define IDC_RADIO_FREE_TEXT             1001
#define IDC_NORMAL_PREDEFINED           1002
#define IDC_EMERGENCY_PREDEFINED        1003
#define IDC_PREDEFINED_CONTENT          1004
#define IDC_SEARCH                      1005
#define IDC_SEARCH_NORMAL               1005
#define IDC_STATION_VERSION_LIST        1005
#define IDC_STATION_FREE_TEXT           1006
#define IDC_VERSION_LIST_MAIN_HEADER    1006
#define IDC_PID_ATTRIBUTES              1007
#define IDC_SPELL_CHECK                 1008
#define IDC_RADIO_NORMAL                1009
#define IDC_RADIO_EMERGENCY             1010
#define IDC_PRIORITY                    1011
#define IDC_DISPLAY_MODE                1012
#define IDC_VERSION_LIST_SUBHEADER      1012
#define IDC_SCROLL_SPEED                1013
#define IDC_JUSTIFICATION               1014
#define IDC_RADIO_TIMED                 1015
#define IDC_RADIO_CONTINUOUS            1016
#define IDC_START_TIME                  1017
#define IDC_END_TIME                    1018
#define IDC_REPEAT_INTERVAL             1019
#define IDC_DISPLAY_TIME                1020
#define IDC_START_DATE                  1020
#define IDC_REPEAT_INTERVAL_ADJUST      1021
#define IDC_END_DATE                    1021
#define IDC_DISPLAY_TIME_ADJUST         1022
#define IDC_LED_FONT_SIZE               1022
#define IDC_SEARCH_EMERGENCY            1023
#define IDC_DISPLAY_TIME_SPIN           1023
#define IDC_LED_FONT_COLOR              1023
#define IDC_PLASMA_FONT_SIZE            1026
#define IDC_PLASMA_FOREGROUND_COLOUR    1027
#define IDC_PLASMA_BACKGROUND_COLOUR    1028
#define IDC_LABEL1                      1029
#define IDC_LABEL2                      1030
#define IDC_LABEL5                      1031
#define IDC_END_TIME_LABEL              1031
#define IDC_LABEL8                      1032
#define IDC_REPEAT_LABEL                1032
#define IDC_LABEL10                     1033
#define IDC_LABEL17                     1034
#define IDC_DISPLAYTIME_LABEL           1034
#define IDC_LABEL11                     1035
#define IDC_LABEL12                     1036
#define IDC_LABEL13                     1037
#define IDC_SCROLLSPEED_LABEL           1037
#define IDC_LABEL14                     1038
#define IDC_JUSTIFICATION_LABEL         1038
#define IDC_LABEL9                      1039
#define IDC_LABEL16                     1040
#define IDC_MINS_LABEL                  1040
#define IDC_NORMAL_LABEL                1041
#define IDC_EMERGENCY_LABEL             1042
#define IDC_CONTENT_LABEL               1043
#define IDC_ISCS_CURRENT_VERSION        1043
#define IDC_ISCS_NEXT_VERSION           1044
#define IDC_LABEL_SEARCH1               1045
#define IDC_LABEL_SEARCH2               1046
#define IDC_COMBO1                      1047
#define IDC_RATIS_TAG                   1047
#define IDC_DISPLAY                     1048
#define IDC_COMBO2                      1048
#define IDC_RATIS_DEST                  1048
#define IDC_LABEL15                     1049
#define IDC_LABEL3                      1050
#define IDC_LABEL4                      1051
#define IDC_MESSAGE_TYPE_TAB            1052
#define IDC_PID_LIST                    1053
#define IDC_LANGUAGES                   1054
#define IDC_BUTTON1                     1055
#define IDC_BUTTON2                     1056
#define IDC_BUTTON3                     1057
#define IDC_MESSAGE_CONTENT             1057
#define IDC_CLEAR_NORMAL                1057
#define IDC_TYPE                        1058
#define IDC_TAG                         1059
#define IDC_CLEAR_ALL                   1061
#define IDC_CLEAR_EMERGENCY             1062
#define IDC_CLEAR_PRIORITY6             1063
#define IDC_CLEAR_RATIS                 1066
#define IDC_FREETEXT_LIST               1067
#define IDC_RECENT_MESSAGES             1068
#define IDC_SAVE                        1069
#define IDC_RATIS_CONTENT               1070
#define IDC_EDIT2                       1074
#define IDC_EDIT3                       1075
#define IDC_UPGRADE_ISCS                1075
#define IDC_EDIT4                       1076
#define IDC_EDIT5                       1077
#define IDC_RADIO2                      1079
#define IDC_RADIO3                      1080
#define IDC_RADIO4                      1081
#define IDC_LANGUAGES_LABEL             1082
#define IDC_MESSAGE_CONTENT_FRAME       1083
#define IDC_DISPLAY_ATTRIBUTES_FRAME    1084
#define IDC_PLASMA_FRAME                1085
#define IDC_LED_FRAME                   1086
#define IDC_MESSAGE_TYPE_FRAME          1087
#define IDC_RATIS_TAG_FRAME             1088
#define IDC_DESTINATION_FRAME           1089
#define IDC_RATIS_CONTENT_FRAME         1090
#define IDC_MAINPAGE_TAB                1092
#define ID_CLOSE                        1093
#define IDC_START_TIME_LABEL            1095
#define IDC_RADIO_NEW                   1097
#define IDC_RADIO_CLEAR                 1098
#define IDC_PROGRESS_CTRL               1099
#define IDC_STATIC_TEXT1                1100
#define IDC_STATIC_TEXT2                1101
#define IDC_STATIC_TEXT3                1102
#define IDC_CLOSE                       1171
#define IDC_HELP_BUTTON                 1172
#define IDC_SAVE_GROUP                  1179
#define IDC_DELETE_GROUP                1180
#define IDC_STN_PID_GROUP_COMBO         1234
#define IDC_EDITNAME                    1284
#define IDC_STATICTEXT                  1288
#define IDC_CHB_OVERRIDE                1289
#define IDC_CHB_VETTING                 1290
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUTSTISMANAGER        32772
#define ID_HELP_STISMANAGERHELP         32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         191
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
