//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by step_plugin.station_tis_step.rc
//
#define IDD_PLAN_STEP_PARAMETER_STATION_TIS_MESSAGE_EDIT_DLG 26379
#define IDD_PLAN_STEP_EDIT_STATION_TIS_DLG           26380
#define IDD_PLAN_STEP_PARAMETER_TIS_PIDLIST_EDIT_DLG 26381
#define IDC_STATIONTIS_LIBRARY_TYPE                26382
#define IDC_STATIONTIS_DEST_LIBRARY_VERSION        26383
#define IDC_STATIONTIS_MSG_LIBRARY_VERSION         26384
#define IDC_STATIONTIS_MESSAGE_LIST                26385
#define IDC_STATIONTIS_STATION_RADIO               26390
#define IDC_STATIONTIS_ALL_STATIONS_RADIO          26391
#define IDC_STATIONTIS_STATION_COMBO               26392
#define IDC_STATIONTIS_STATION_LEVEL_COMBO         26393
#define IDC_STATIONTIS_PICK_PID_BUTTON             26394
#define IDC_STATIONTIS_MESSAGE_EDIT                26395
#define IDC_STATIONTIS_PICK_MESSAGE_BUTTON         26396
#define IDC_STATIONTIS_PRIORITY_COMBO              26397
#define IDC_STATIONTIS_PID_LIST                    26398
#define IDC_STATIONTIS_DURATION_PICKER             26399
#define IDC_STATIONTIS_PID_LIST_CHECK              26400
#define IDC_STATIONTIS_STATION_LEVEL_CHECK         26401
#define IDC_STATIONTIS_AVAILABLE_PID_LIST          26402
#define IDC_STATIONTIS_ADD_SELECTION_BUTTON        26403
#define IDC_STATIONTIS_REMOVE_SELECTION_BUTTON     26404
#define IDC_STATIONTIS_ADD_ALL_BUTTON              26405
#define IDC_STATIONTIS_REMOVE_ALL_BUTTON           26406
#define IDC_STATIONTIS_SELECTED_PID_LIST           26407
#define IDC_STATIONTIS_PARAMETER_NAME              26408
#define IDS_STATIONTIS_STEP_PARAMETER_STATION            26410
#define IDS_STATIONTIS_STEP_PARAMETER_TIS_STATION_LEVEL  26411
#define IDS_STATIONTIS_STEP_PARAMETER_TIS_PID_LIST       26412
#define IDS_STATIONTIS_STEP_PARAMETER_TIS_MESSAGE        26413
#define IDS_STATIONTIS_STEP_PARAMETER_TIS_PRIORITY       26414
#define IDS_STATIONTIS_STEP_PARAMETER_TIS_DURATION       26415

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        27000
#define _APS_NEXT_COMMAND_VALUE         27001
#define _APS_NEXT_CONTROL_VALUE         27002
#define _APS_NEXT_SYMED_VALUE           27003
#endif
#endif
