@ECHO OFF
SET FZL1=C:\C0de\FZL1_TIP_b2\TA_BASE\code
SET COMM=C:\C0de\TA_Common_V1_TIP_b2\code
junction %FZL1%\cots														C:\COTS
junction %FZL1%\tools														%COMM%\tools
junction %FZL1%\transactive\bus												%COMM%\transactive\bus
junction %FZL1%\transactive\core											%COMM%\transactive\core
junction %FZL1%\transactive\app\alarm\alarm_agent							%COMM%\transactive\app\alarm\alarm_agent
junction %FZL1%\transactive\app\alarm\alarm_raiser							%COMM%\transactive\app\alarm\alarm_raiser
junction %FZL1%\transactive\app\alarm\alarm_store_service					%COMM%\transactive\app\alarm\alarm_store_service
junction %FZL1%\transactive\app\alarm\AlarmSharedMapReader					%COMM%\transactive\app\alarm\AlarmSharedMapReader
junction %FZL1%\transactive\app\alarm\AlarmStoreHarness						%COMM%\transactive\app\alarm\AlarmStoreHarness
junction %FZL1%\transactive\app\alarm\ATSInterface							%COMM%\transactive\app\alarm\ATSInterface
junction %FZL1%\transactive\app\checker										%COMM%\transactive\app\checker
junction %FZL1%\transactive\app\datalog										%COMM%\transactive\app\datalog
junction %FZL1%\transactive\app\dbsynch										%COMM%\transactive\app\dbsynch
junction %FZL1%\transactive\app\event\ATSBridgeUtil							%COMM%\transactive\app\event\ATSBridgeUtil
junction %FZL1%\transactive\app\event\event_agent							%COMM%\transactive\app\event\event_agent
junction %FZL1%\transactive\app\event\event_extractor						%COMM%\transactive\app\event\event_extractor
junction %FZL1%\transactive\app\event\EventGenerator						%COMM%\transactive\app\event\EventGenerator
junction %FZL1%\transactive\app\event\EventViewerSimulator					%COMM%\transactive\app\event\EventViewerSimulator
junction %FZL1%\transactive\app\event\online_printing_agent					%COMM%\transactive\app\event\online_printing_agent
junction %FZL1%\transactive\app\notification_service						%COMM%\transactive\app\notification_service
junction %FZL1%\transactive\app\response_plans\plan_agent					%COMM%\transactive\app\response_plans\plan_agent
junction %FZL1%\transactive\app\response_plans\plan_agent_test				%COMM%\transactive\app\response_plans\plan_agent_test
junction %FZL1%\transactive\app\response_plans\plan_mft_processor			%COMM%\transactive\app\response_plans\plan_mft_processor
junction %FZL1%\transactive\app\response_plans\plan_step_plugin				%COMM%\transactive\app\response_plans\plan_step_plugin
junction %FZL1%\transactive\app\scada\DataNodeAgent							%COMM%\transactive\app\scada\DataNodeAgent
junction %FZL1%\transactive\app\scada\DataNodeController					%COMM%\transactive\app\scada\DataNodeController
junction %FZL1%\transactive\app\scada\ModbusAgent							%COMM%\transactive\app\scada\ModbusAgent
junction %FZL1%\transactive\app\scada\ModbusServerAgent						%COMM%\transactive\app\scada\ModbusServerAgent
junction %FZL1%\transactive\app\scada\OpcBridgeLib							%COMM%\transactive\app\scada\OpcBridgeLib
junction %FZL1%\transactive\app\scada\OpcBridgeService						%COMM%\transactive\app\scada\OpcBridgeService
junction %FZL1%\transactive\app\scada\PMSAgent								%COMM%\transactive\app\scada\PMSAgent
junction %FZL1%\transactive\app\scada\PowerDemandEditor						%COMM%\transactive\app\scada\PowerDemandEditor
junction %FZL1%\transactive\app\scada\PScadaAgent							%COMM%\transactive\app\scada\PScadaAgent
junction %FZL1%\transactive\app\scada\SNMPStatusAgent						%COMM%\transactive\app\scada\SNMPStatusAgent
junction %FZL1%\transactive\app\scada\VirtualDataPointAgent					%COMM%\transactive\app\scada\VirtualDataPointAgent
junction %FZL1%\transactive\app\scheduling\scheduling_agent					%COMM%\transactive\app\scheduling\scheduling_agent
junction %FZL1%\transactive\app\security\authentication_agent				%COMM%\transactive\app\security\authentication_agent
junction %FZL1%\transactive\app\security\duty_agent							%COMM%\transactive\app\security\duty_agent
junction %FZL1%\transactive\app\security\rights_agent						%COMM%\transactive\app\security\rights_agent
junction %FZL1%\transactive\app\security\rights_service						%COMM%\transactive\app\security\rights_service
junction %FZL1%\transactive\app\simulator									%COMM%\transactive\app\simulator
junction %FZL1%\transactive\app\sound										%COMM%\transactive\app\sound
junction %FZL1%\transactive\app\system_control\dll_host						%COMM%\transactive\app\system_control\dll_host
junction %FZL1%\transactive\app\system_control\dummy_agent					%COMM%\transactive\app\system_control\dummy_agent
junction %FZL1%\transactive\app\system_control\system_controller			%COMM%\transactive\app\system_control\system_controller
junction %FZL1%\transactive\app\system_control\system_status_agent			%COMM%\transactive\app\system_control\system_status_agent
junction %FZL1%\transactive\app\system_control\transact_screensaver			%COMM%\transactive\app\system_control\transact_screensaver
junction %FZL1%\transactive\app\train_timetable								%COMM%\transactive\app\train_timetable
junction %FZL1%\transactive\app\trending									%COMM%\transactive\app\trending
junction %FZL1%\transactive\app\WebPortal									%COMM%\transactive\app\WebPortal
