///////////////////////////////////////////////////////////
//
//  RadioConnectionException.cpp
//  Implementation of the Class RadioConnectionException
//  Generated by Enterprise Architect
//  Created on:      29-Oct-2003 17:47:05
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "app/radio/RadioTetraAgent/RadioTcpCommunication/src/TcpConnectionException.h"

using namespace TA_IRS_App;

TcpConnectionException::TcpConnectionException() throw()
  : TcpException("No Connection to Radio")
{
}


TcpConnectionException::~TcpConnectionException() throw()
{
}


