//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by step_plugin.train_pa_step.rc
//
#define IDD_TRAINPA_PA_STATION_MESSAGE_DLG 26469
#define IDD_PLAN_STEP_PA_TRAIN_DLG      26470
#define IDC_TRAINPA_CYCLIC_CHECK                26480
#define IDC_TRAINPA_PA_TRAIN_GROUPES_COMBO      26481
#define IDC_TRAINPA_DURATION_DTPICKER           26482
#define IDC_TRAINPA_PA_TRAINS_COMBO             26483
#define IDC_TRAINPA_PA_TRAIN_MESSAGE_TXT        26484
#define IDC_TRAINPA_PA_TRAIN_MSG_DLG_BTN        26485
#define IDC_TRAINPA_PARAMETER_NAME_TXT          26486
#define IDC_TRAINPA_LIB_SECTION_TXT             26487
#define IDC_TRAINPA_LIB_VERSION_TXT             26488
#define IDC_TRAINPA_MESSAGES_LIST               26489
#define IDS_TRAINPA_STEP_PARAMETER_PA_CYCLIC    26490
#define IDS_TRAINPA_STEP_PARAMETER_PA_MESSAGE   26491
#define IDS_TRAINPA_STEP_PARAMETER_TRAIN        26492
#define IDS_TRAINPA_STEP_PARAMETER_PA_DURATION 26493

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        27000
#define _APS_NEXT_COMMAND_VALUE         27001
#define _APS_NEXT_CONTROL_VALUE         27002
#define _APS_NEXT_SYMED_VALUE           27003
#endif
#endif
