// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "imos_mediaocxctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CImos_mediaocxctrl1

IMPLEMENT_DYNCREATE(CImos_mediaocxctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CImos_mediaocxctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CImos_mediaocxctrl1 operations
