//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoDisplayManager.rc
//
#define IDS_PROPSHT_CAPTION             2
#define IDD_VIDEODISPLAYMANAGER_DIALOG  102
#define IDD_VIDEODISPLAYMANAGER_DIALOG_IMOS 102
#define IDR_MAINFRAME                   128
#define IDB_TRAINCAMRIGHT               129
#define IDB_TRAINCAMLEFT                130
#define IDB_TRAINCAMRIGHT_HILITE        131
#define IDB_TRAINCAMLEFT_HILITE         132
#define IDB_VMON_HILITE                 133
#define IDB_VMON                        134
#define IDB_QUADVMON                    135
#define IDB_QUADVMON_HILITE             136
#define IDI_CAMERA                      137
#define IDI_CLOSEDFOLDER                138
#define IDI_OPENFOLDER                  139
#define IDI_SEQUENCE                    140
#define IDI_QUAD                        141
#define IDB_VCR                         142
#define IDB_VCR_HILITE                  143
#define IDB_SINGLEVMON                  144
#define IDB_SINGLEVMON_HILITE           145
#define IDB_ODS                         146
#define IDB_ODS_HILITE                  147
#define IDC_DRAG_CURSOR                 148
#define IDD_CAMERAS                     149
#define IDD_QUADS                       150
#define IDD_SEQUENCES                   151
#define IDR_MONCAMCONTEXT_MENU          155
#define IDD_SEQUENCEEDITOR_DIALOG       156
#define IDI_ADD                         157
#define IDI_REMOVE                      158
#define IDI_TOP                         159
#define IDI_UP                          160
#define IDI_DOWN                        161
#define IDI_BOTTOM                      162
#define IDD_RECORDINGUNIT_DIALOG        163
#define IDR_MAIN_MENU                   164
#define IDI_PLAY_ICON                   165
#define IDR_QUADCONTEXT_MENU            165
#define IDI_HALT_ICON                   166
#define IDI_PAUSE_ICON                  167
#define IDI_NEXTELEMENT_FF_ICON         168
#define IDI_RECORD_ICON                 169
#define IDI_PREVIOUSELEMENT_RW_ICON     170
#define IDD_QUADCONTROLLER_DIALOG       172
#define IDB_QUADSEG                     173
#define IDB_QUADSEG_HILITE              175
#define IDD_TRAINS                      177
#define IDI_TRAIN                       178
#define IDD_TRAINBORNECONTROLLER        181
#define IDB_SINGLEVMON_DISABLED         182
#define IDB_QUADVMON_DISABLED           183
#define IDR_MONQUADCONTEXT_MENU         184
#define IDR_MONSEQCONTEXT_MENU          185
#define IDR_MONTRAINCONTEXT_MENU        186
#define IDR_VCRCONTEXT_MENU             187
#define IDR_PAGEQUADCONTEXT_MENU        188
#define IDR_PAGESEQCONTEXT_MENU         189
#define IDR_PAGETRAINCONTEXT_MENU       190
#define IDB_SINGLEVMON_FORTRAIN         191
#define IDB_SINGLEVMON_FORTRAIN_HILITE  192
#define IDD_SAVEAS_DIALOG               193
#define IDR_MONALARMCONTEXT_MENU        194
#define IDD_DLG_INITPROGRESS            195
#define IDD_LOCATION_SELECTION          196
#define IDD_STATIONDISPLAY_DIALOG       197
#define IDD_STATIONDISPLAY_DIALOG_IMOS  197
#define IDB_BITMAP1                     198
#define IDI_ZOOM_OUT                    203
#define IDI_EAST_ARROW                  204
#define IDI_WEST_ARROW                  205
#define IDI_NORTH_ARROW                 206
#define IDI_SOUTH_ARROW                 207
#define IDI_ZOOM_IN                     208
#define IDI_PT_NW_ICON                  210
#define IDI_PT_NE_ICON                  213
#define IDI_PT_SE_ICON                  214
#define IDI_PT_SW_ICON                  215
#define IDI_ZOOM_IN_ICON                216
#define IDI_ZOOM_OUT_ICON               218
#define IDD_VIDEO_PLAY_IMOS             220
#define IDR_VIDEO_CONTROL               221
#define IDD_TEST_DLG                    222
#define IDI_UNKNOW                      225
#define IDI_BACKUP                      226
#define IDI_UNLOCK                      227
#define IDD_VIDEO_PLAY_MODBUS           228
#define IDD_VIDEODISPLAYMANAGER_DIALOG_MODBUS_OCC 229
#define IDD_VIDEODISPLAYMANAGER_DIALOG_MODBUS 229
#define IDD_STATIONDISPLAY_DIALOG1      231
#define IDD_STATIONDISPLAY_DIALOG_MODBUS_STATION 231
#define IDD_STATIONDISPLAY_DIALOG_MODBUS 231
#define IDC_COMMON_BOX                  1002
#define IDC_WALL_MONITOR_1              1004
#define IDC_WALL_MONITOR_2              1005
#define IDC_WALL_MONITOR_3              1006
#define IDC_QUAD1                       1007
#define IDC_WALL_MONITOR_7              1007
#define IDC_WALL_MONITOR_4              1008
#define IDC_QUAD5                       1008
#define IDC_WALL_MONITOR_5              1009
#define IDC_QUAD9                       1009
#define IDC_WALL_MONITOR_6              1010
#define IDC_CONSOLE_MONITOR_1           1011
#define IDC_QUAD3                       1012
#define IDC_WALL_MONITOR_8              1012
#define IDC_QUAD2                       1013
#define IDC_WALL_MONITOR_9              1013
#define IDC_QUAD4                       1014
#define IDC_WALL_MONITOR_10             1014
#define IDC_LABEL_WALL_MONITOR_1        1015
#define IDC_LOCAL_MONITOR               1015
#define IDC_LABEL_WALL_MONITOR_2        1016
#define IDC_QUAD6                       1016
#define IDC_LABEL_WALL_MONITOR_3        1017
#define IDC_QUAD7                       1017
#define IDC_LABEL_OVERVIEW_DISPLAY      1018
#define IDC_QUAD8                       1018
#define IDC_LABEL_WALL_MONITOR_4        1019
#define IDC_LOCAL_MONITOR2              1019
#define IDC_LABEL_WALL_MONITOR_5        1020
#define IDC_QUAD10                      1020
#define IDC_LABEL_WALL_MONITOR_6        1021
#define IDC_QUAD11                      1021
#define IDC_WALL_MONITOR_11             1022
#define IDC_QUAD12                      1022
#define IDC_WALL_MONITOR_12             1023
#define IDC_LOCAL_MONITOR3              1023
#define IDC_WALL_MONITOR_13             1024
#define IDC_WALL_MONITOR_14             1025
#define IDC_CAMERATREE                  1026
#define IDC_WALL_MONITOR_15             1026
#define IDC_QUADTREE                    1027
#define IDC_WALL_MONITOR_16             1027
#define IDC_SEQUENCETREE                1028
#define IDC_LABEL_WALL_MONITOR_7        1028
#define IDC_TEXT_WALL_MONITOR_1         1029
#define IDC_TEXT_WALL_MONITOR_2         1030
#define IDC_TEXT_WALL_MONITOR_3         1031
#define IDC_TEXT_WALL_MONITOR_7         1032
#define IDC_TEXT_WALL_MONITOR_4         1033
#define IDC_TEXT_WALL_MONITOR_5         1034
#define IDC_TEXT_WALL_MONITOR_6         1035
#define IDC_TEXT_WALL_MONITOR_8         1036
#define IDC_TEXT_CONSOLE_MONITOR_2      1037
#define IDC_SE_DESCRIPTION_EDIT_BOX     1038
#define IDC_TEXT_WALL_MONITOR_9         1038
#define IDC_SE_DWELLTIME_LABEL          1039
#define IDC_TEXT_WALL_MONITOR_10        1039
#define IDC_LABEL_WALL_MONITOR_8        1040
#define IDC_SE_DWELLTIME_EDIT_BOX       1041
#define IDC_LABEL_WALL_MONITOR_9        1041
#define IDC_SE_DESCRIPTION_LABEL        1042
#define IDC_LABEL_WALL_MONITOR_10       1042
#define IDC_SE_ADD_BUTTON               1043
#define IDC_LABEL_WALL_MONITOR_11       1043
#define IDC_SE_REMOVE_BUTTON            1044
#define IDC_LABEL_WALL_MONITOR_12       1044
#define IDC_SE_SOURCES_INSEQUENCE_LABEL 1045
#define IDC_TEXT_WALL_MONITOR_11        1045
#define IDC_SE_SEQUENCES_LIST           1046
#define IDC_TEXT_WALL_MONITOR_12        1046
#define IDC_SE_TOP_BUTTON               1047
#define IDC_TEXT_WALL_MONITOR_13        1047
#define IDC_SE_UP_BUTTON                1048
#define IDC_TEXT_WALL_MONITOR_14        1048
#define IDC_SE_DOWN_BUTTON              1049
#define IDC_TEXT_WALL_MONITOR_15        1049
#define IDC_SE_BOTTOM_BUTTON            1050
#define IDC_TEXT_WALL_MONITOR_16        1050
#define IDC_SE_SECONDS_LABEL            1051
#define IDC_WALL_MONITOR_17             1051
#define IDC_SE_SAVE_BUTTON              1052
#define IDC_WALL_MONITOR_18             1052
#define IDC_SE_CAMERATREE               1053
#define IDC_WALL_MONITOR_19             1053
#define ID_SE_AVAILABLECAMERAS_LABEL    1054
#define IDC_WALL_MONITOR_20             1054
#define IDC_TEXT_WALL_MONITOR_17        1055
#define IDC_RU_RECORDINGUNIT_EDIT       1056
#define IDC_TEXT_WALL_MONITOR_18        1056
#define IDC_RU_MONITOR_EDIT             1057
#define IDC_TEXT_WALL_MONITOR_19        1057
#define IDC_TEXT_WALL_MONITOR_20        1058
#define IDC_RU_PLAY_CHECK               1059
#define IDC_CONSOLE_MONITOR_2           1059
#define IDC_LABEL_OVERVIEW_DISPLAY2     1060
#define IDC_MENU_LINE                   1061
#define IDC_TEXT_CONSOLE_MONITOR_3      1062
#define IDC_CONSOLE_MONITOR_3           1063
#define IDC_LABEL_OVERVIEW_DISPLAY3     1064
#define IDC_SC_HALT_BUTTON              1065
#define IDC_TEXT_CONSOLE_MONITOR_4      1065
#define IDC_CONSOLE_MONITOR_4           1066
#define IDC_LABEL_OVERVIEW_DISPLAY4     1067
#define IDC_TEXT_CONSOLE_MONITOR_5      1068
#define IDC_CONSOLE_MONITOR_5           1069
#define IDC_RU_RECORD_CHECK             1070
#define IDC_LABEL_OVERVIEW_DISPLAY5     1070
#define IDC_RU_REWIND_CHECK             1071
#define IDC_TEXT_CONSOLE_MONITOR_6      1071
#define IDC_RU_STOP_CHECK               1072
#define IDC_RU_FAST_FORWARD_CHECK       1073
#define IDC_RU_PAUSE_CHECK              1074
#define IDC_QC_CAMERATREE               1075
#define IDC_QC_APPLY_BUTTON             1076
#define IDC_QUADSEG1                    1078
#define IDC_QUADSEG2                    1079
#define IDC_QUADSEG3                    1080
#define IDC_QUADSEG4                    1081
#define IDC_TEXT_QUADSEG_1              1082
#define IDC_TEXT_QUADSEG_2              1083
#define IDC_TEXT_QUADSEG_3              1084
#define IDC_TEXT_QUADSEG_4              1085
#define ID_QC_AVAILABLECAMERAS_LABEL    1086
#define IDC_SEQUENCENAMEDESC_EDIT       1087
#define IDC_TRAINSLIST_IB               1088
#define IDC_TC_TRAIN_LABEL              1089
#define IDC_TRAINCAR1                   1090
#define IDC_TRAINSLIST_OB               1090
#define IDC_TRAINCAR2                   1091
#define IDC_TRAINCAR3                   1092
#define IDC_QUADRADIO                   1095
#define IDC_SINGLERADIO                 1096
#define IDC_SEQUENCERADIO               1097
#define IDC_SEQUENCECOMBO               1098
#define IDC_TRAINSINGLEMON              1099
#define IDC_TRAINQUADMON1               1100
#define IDC_TRAINQUADMON2               1101
#define IDC_TRAINQUADMON3               1102
#define IDC_TRAINQUADMON4               1103
#define IDC_TC_APPLY_BUTTON             1105
#define IDC_TRAINCAM1                   1106
#define IDC_TRAINCAM2                   1107
#define IDC_TRAINCAM3                   1108
#define IDC_TRAINCAM4                   1109
#define IDC_TRAINCAM5                   1110
#define IDC_TRAINCAM6                   1111
#define IDC_TRAINCAM7                   1112
#define IDC_TRAINCAM8                   1113
#define IDC_CAM1_LABEL                  1114
#define IDC_CAM2_LABEL                  1115
#define IDC_DWELLTIME_SPIN              1115
#define IDC_CAM3_LABEL                  1116
#define IDC_CAM4_LABEL                  1117
#define IDC_CAM5_LABEL                  1118
#define IDC_CAM6_LABEL                  1119
#define IDC_CAM7_LABEL                  1120
#define IDC_CAM8_LABEL                  1121
#define IDC_SINGLEMON_TEXT              1122
#define IDC_QUAD1_TEXT                  1123
#define IDC_QUAD2_TEXT                  1124
#define IDC_QUAD3_TEXT                  1125
#define IDC_QUAD4_TEXT                  1126
#define IDC_SAVEAS_SEQUENCETREE         1126
#define IDC_QUAD1_TEXT2                 1127
#define IDC_QUAD3_TEXT2                 1128
#define IDC_QUAD2_TEXT2                 1129
#define IDC_QUAD4_TEXT2                 1130
#define IDC_PROGRESS_CTRL               1131
#define IDC_QUAD1_TEXT3                 1131
#define IDC_STATIC_TEXT1                1132
#define IDC_QUAD3_TEXT3                 1132
#define IDC_STATIC_TEXT2                1133
#define IDC_QUAD2_TEXT3                 1133
#define IDC_STATIC_TEXT3                1134
#define IDC_QUAD4_TEXT3                 1134
#define IDC_LOCSEL_COMBOBOX_LOCATIONS   1135
#define IDC_GF_SEQUENCE_OCC             1145
#define IDC_STATION_MONITOR_GROUP       1146
#define IDC_GF_OCC_SEQ_STATION_COMB     1147
#define IDC_STATION_MONITOR_GROUP2      1147
#define IDC_MON_GROUP_STATION_1         1147
#define IDC_GF_SEQENCE_TREE             1148
#define IDC_STATION_MONITOR_GROUP3      1148
#define IDC_MON_GROUP_STATION_2         1148
#define IDC_GF_OCC_SEL_STATION_COMB     1149
#define IDC_GF_EDIT_SEQ_BTN             1150
#define IDC_GF_SEQ_LST                  1151
#define IDC_STATION_SEQUENCE_GROUP      1152
#define IDC_GF_OCC_STATION_PIC          1153
#define IDC_STATION_SEQ_STATION_COMB    1154
#define IDC_STATION_SEQENCE_TREE        1155
#define IDC_STATION_EDIT_SEQ_BTN        1156
#define IDC_STATION_SEQ_LST             1157
#define IDC_STATION_PTZ_GROUP           1158
#define IDC_STATION_SEL_STATION_COMB    1159
#define IDC_STATION_STATION_PIC         1160
#define IDC_STATION_PIC_GROUP           1161
#define IDC_PT_LEFT_UP_BTN              1162
#define IDC_TILT_UP_BTN                 1163
#define IDC_PT_RIGHT_UP_BTN             1164
#define IDC_PAN_RIGHT_BTN               1165
#define IDC_PT_RIGHT_DOWN_BTN           1166
#define IDC_TILT_DOWN_BTN               1167
#define IDC_PT_LEFT_DOWN_BTN            1168
#define IDC_PAN_LEFT_BTN                1169
#define IDC_ZOOM_OUT_BTN                1170
#define IDC_ZOOM_IN_BTN                 1171
#define IDC_STATIC_QUAD                 1172
#define IDC_LOCAL_MONITOR_TEXT          1173
#define IDC_LOCAL_MONITOR_TEXT2         1174
#define IDC_STATIC_QUAD2                1175
#define IDC_LOCAL_MONITOR_TEXT3         1176
#define IDC_STATIC_QUAD3                1177
#define IDC_QUAD1_INDEX                 1179
#define IDC_QUAD2_INDEX                 1180
#define IDC_QUAD3_INDEX                 1181
#define IDC_QUAD4_INDEX                 1182
#define IDC_QUAD1_INDEX2                1183
#define IDC_OPC_MONITOR_DESC            1184
#define IDC_QUAD3_INDEX2                1184
#define IDC_OPC_MONITOR_DESC2           1185
#define IDC_QUAD2_INDEX2                1185
#define IDC_QUAD4_INDEX2                1186
#define IDC_OPC_MONITOR_DESC4           1187
#define IDC_QUAD1_INDEX3                1187
#define IDC_COM_PAN_SPEED               1188
#define IDC_QUAD3_INDEX3                1188
#define IDC_COM_TILT_SPEED              1189
#define IDC_BUTTON1                     1189
#define IDC_OPC_MONITOR_DESC6           1189
#define IDC_QUAD2_INDEX3                1189
#define IDC_BUTTON2                     1190
#define IDC_QUAD4_INDEX3                1190
#define IDC_BUTTON3                     1191
#define IDC_OPC_MONITOR_DESC8           1191
#define IDC_BUTTON4                     1192
#define IDC_BUTTON5                     1193
#define IDC_OPC_MONITOR_DESC10          1193
#define IDC_BUTTON6                     1194
#define IDC_BUTTON7                     1195
#define IDC_BUTTON8                     1196
#define IDC_IMOS_MEDIAOCXCTRL1          1197
#define IDC_STAION_OFFICE_BTN           1198
#define IDC_UP_PLT_BTN                  1199
#define IDC_DOWN_PLT_BTN                1200
#define IDC_B1_BTN                      1201
#define IDC_B2_BTN                      1202
#define IDC_PARAM                       1204
#define IDC_PARAM_VALUE                 1205
#define IDC_ACTIVEXCLIENTCTRL1          1206
#define IDC_MON_GROUP_LOCAL             1207
#define IDC_MON_GROUP_OPS1              1208
#define IDC_MON_GROUP_OPS2              1209
#define IDC_MON_GROUP_OPS3              1210
#define IDC_MON_GROUP_OPS4              1211
#define IDC_MON_GROUP_STATION_LOCAL     1212
#define IDC_SCHEMATIC_SEL_LIST          1213
#define ID_LOAD_CONTROLLER              32771
#define ID_CLEAR_MONITOR                32772
#define ID_NEW_EDIT_SEQUENCE            32773
#define ID_DEACTIVATE_TRAIN             32774
#define ID_APP_HELP                     32775
#define ID_TIMELAPSE_MODE               32776
#define ID_REALTIME_MODE                32777
#define ID_VIDEO_CONTROL_STOP           32782
#define IDS_UE010016_CANNOT_LOAD_DATA   57665

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1214
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
