//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InspectorPanel.rc
//
#define IDS_ABOUTBOX                    1
#define IDS_ENABLE_DATAPOINT            2
#define IDS_DISABLE_DATAPOINT           3
#define IDS_APPLY_TAG_CHANGES           4
#define IDS_SCAN_INHIBIT                5
#define IDS_ALARM_INHIBIT               6
#define IDS_MMS_INHIBIT                 7
#define IDS_CONTROL_INHIBIT             8
#define IDS_OVERRIDE                    9
#define IDS_REMOVE_EQUIPMENT_STATUS     10
#define IDS_UPDATE_EQUIPMENT_STATUS     11
#define IDS_REMOVE_EQUIPMENT_NOTES      12
#define IDS_UPDATE_EQUIPMENT_NOTES      13
#define IDS_OVERRIDE_ALARM_ENABLED      14
#define IDS_OVERRIDE_ALARM_THRESHOLD    15
#define IDS_LOADING_DATA_NODE           16
#define IDS_LOADING_DATA_POINT          17
#define IDS_LOADING_COMPLETE            18
#define IDD_INSPECTOR_PANEL_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_INFORMATION                 129
#define IDD_CONTROL                     130
#define IDD_TAG                         131
#define IDB_GREEN                       132
#define IDD_LIMITS                      134
#define IDD_CONFIRM_CONTROL_DIALOG      136
#define IDD_CONFIRM_TAG_DIALOG          137
#define IDD_MAINTENANCE                 138
#define IDD_NOTES                       139
#define IDD_CONFIRM_OVERRIDE_DIALOG     144
#define IDD_STATUS                      145
#define IDD_INHIBIT                     146
#define IDD_OVERRIDE                    147
#define IDD_METER                       148
#define IDD_CONFIRM_ADJUST_DIALOG       149
#define IDD_CONFIRM_DIRECT_CONTROL_DIALOG 150
#define IDI_GREY                        151
#define IDI_GREEN                       152
#define IDI_RED                         153
#define IDI_ORANGE                      154
#define IDI_BLUE                        155
#define IDD_PSCADA_CONTROL              156
#define IDD_INPUT_VALUE_DIALOG          157
#define IDC_MAINTAB                     1000
#define IDC_EQUIPMENT_DESCRIPTION       1001
#define IDC_HELP_BUTTON                 1002
#define IDC_INFO_DATAPOINTLIST          1004
#define IDC_CONTROLLIST                 1004
#define IDC_LIMITS_DETAILSLIST          1005
#define IDC_PTW_ID                      1009
#define IDC_COMMENT                     1010
#define IDC_APPLY_TAG                   1012
#define IDC_EDITNOTES                   1013
#define IDC_LIMIT_INFO                  1014
#define IDC_STATUS_INFO                 1015
#define IDC_BUTTON1                     1016
#define IDC_REMOVE                      1017
#define IDC_RADIO_NOT_TAGGED            1036
#define IDC_RADIO_TAG                   1037
#define IDC_RADIO_TAG_PTW               1038
#define IDC_COUNT                       1041
#define IDC_STATUS                      1042
#define IDC_EQUIPMENT                   1043
#define IDC_DATA_POINT                  1044
#define IDC_NEW_VALUE                   1045
#define IDC_VALUE_UNIT                  1046
#define IDC_INFO_MAINTENANCELIST        1053
#define IDC_STATUS_GROUP_BOX            1054
#define IDC_UPDATE                      1055
#define IDC_TAG                         1056
#define IDC_INHIBIT                     1057
#define IDC_HELPBUTTON                  1059
#define IDC_SCANINHIBIT_CHECK           1060
#define IDC_CONTROLINHIBIT_CHECK2       1061
#define IDC_OVERRIDE_DATAPOINTLIST      1061
#define IDC_CONTROLINHIBIT_CHECK        1061
#define IDC_ALARMINHIBIT_CHECK3         1062
#define IDC_INHIBIT_DATAPOINTLIST       1062
#define IDC_ALARMINHIBIT_CHECK          1062
#define IDC_MMSINHIBIT_CHECK            1063
#define IDC_METER_DATAPOINTLIST         1063
#define IDCONFIRM                       1065
#define ID_HELP_CA                      1066
#define ID_HELP_CC                      1067
#define ID_HELP_CO                      1068
#define ID_HELP_CT                      1069
#define ID_HELP_IP                      1070
#define IDC_STATIC1                     1073
#define IDC_STATIC2                     1074
#define IDC_STATIC3                     1075
#define IDC_STATIC4                     1076
#define IDC_INPUT_NEW_VALUE             1077
#define IDC_COMBO1                      1080
#define IDC_COMBOBOX_VALUE              1080
#define IDS_LOADING                     2000
#define IDS_INSPECTORPANEL_TITLE        2001
#define IDS_LOADING_NODE_PROXY          2004
#define IDS_LOADING_NODE_PROXY_FAILED   2005                            
#define IDS_LOADING_NODE_FAILED         2006
#define IDS_LOADING_DATA_POINT_FAILED   2007
#define IDS_LOADING_DATA_PROXY          2008
#define IDS_LOADING_DATA_PROXY_FAILED   2009
#define IDS_CONFIRM_CANCLE              2010
#define IDS_EQUIPMENT                   2011
#define IDS_CONTROL_POINT               2012
#define IDS_CONTROL_ACTION              2013
#define IDS_CONTROL_INFO                2014
#define IDS_CONFIRM                     2015
#define IDS_CANCEL                      2016
#define IDS_DESCRIPTION_COLUMN          2017
#define IDS_TYPE_COLUMN                 2018
#define IDS_STATE_COLUMN                2019
#define IDS_OPERATION_COLUMN            2020
#define IDS_SETUP                       2021
#define IDS_SENT                        2022
#define IDS_PENDING                     2023
#define IDS_SUCCESSFUL                  2024
#define IDS_FAILED                      2025
#define IDS_LCC_FAILED                  2026
#define IDS_RCC_FAILED                  2027
#define IDS_COMMS_FAILED                2028
#define IDS_SELECT_COMMAND_WRITE        2029
#define IDS_SELECT_COMMAND_CONFIRM      2030
#define IDS_SELECT_COMMAND_TIMEOUT      2031
#define IDS_OPERATOR_TIMEOUT            2032
#define IDS_EXE_COMMAND_WRITE           2033
#define IDS_EXE_COMMAND_CONFIRM         2034
#define IDS_EXE_COMMAND_TIMEOUT         2035
#define IDS_EXE_COMMAND_SUCCESS         2036
#define IDS_EXE_COMMAND_SUCCESS_TIMEOUT 2037
#define IDS_CANCEL_COMMAND_WRITE        2038
#define IDS_CANCEL_COMMAND_CONFIRM      2039
#define IDS_CANCEL_COMMAND_TIMEOUT      2040
#define IDS_SELECT_COMMAND_NEGATIVE     2041
#define IDS_EXE_COMMAND_NEGATIVE        2042
#define IDS_CANCEL_COMMAND_NEGATIVE     2043
#define IDS_COMMAND_EXCEPTION           2044
#define IDS_SEND_COMMAND_NO_PERMISSION  2045
#define IDS_SET_FAILED_NO_PERMISSION    2046
#define IDS_CURRENT_VALUE_COLUMN        2047
#define IDS_SELECT_ACTION               2048
#define IDS_EXEC_ACTION                 2049
#define IDS_CANCEL_ACTION               2050
#define IDS_VALUE_INVALID               2051
#define IDS_VALUE_OUT_RANGE             2052
#define IDS_VALUE_RANGE                 2053
#define IDS_INVALID_NUM_MSG             2054
#define IDS_INVALID_VALUE_MSG           2055
#define IDS_NO_PERMISSION_MSG           2056
#define IDS_CONTROL_INHIBITED_MSG       2057
#define IDS_SET_NEW_VALUE_MSG           2058
#define IDS_SET_FAILED_PROXY_MSG        2059
#define IDS_SET_FAILED_UNKNOWN_MSG      2060
#define IDS_QUALITY_COLUMN              2061
#define IDS_TIME_COLUMN                 2062
#define IDS_DATA_GOOD                   2063
#define IDS_DATA_GOOD_OVERRIDE          2064
#define IDS_DATA_BAD                    2065
#define IDS_DATA_BAD_NO_CONECT          2066
#define IDS_DATA_BAD_LAST_KNOWN         2067
#define IDS_DATA_BAD_CFG                2068
#define IDS_DATA_BAD_DEVICE             2069
#define IDS_DATA_BAD_SENSOR             2070
#define IDS_DATA_BAD_COMM               2071
#define IDS_DATA_BAD_SERVICE            2072
#define IDS_DATA_UNCERTAIN              2073
#define IDS_DATA_UNCERTAIN_LAST_KNOWN   2074
#define IDS_DATA_UNCERTAIN_SENSOR       2075
#define IDS_DATA_UNCERTAIN_EXCEED       2076
#define IDS_DATA_UNCERTAIN_SUB_NORMAL   2077
#define IDS_CONTROL_COLUMN              2078
#define IDS_SCAN_INHIBIT_MSG            2079
#define IDS_ON_MSG                      2080
#define IDS_OFF_MSG                     2081
#define IDS_ALARM_INHIBIT_MSG           2082
#define IDS_CONTROL_INHIBIT_MSG         2083
#define IDS_CHANGEING_EQUIPMENT_MSG     2084
#define IDS_ALARM_TYPE_COLUMN           2085
#define IDS_ENABLE_COLUMN               2086
#define IDS_THRESHOLD_COLUMN            2087
#define IDS_ALARM_TYPE                  2088
#define IDS_ALARM_ENABLE_MSG            2089
#define IDS_ALARM_DISABLE_MSG           2090
#define IDS_SET_UNIT_ERR_MSG            2091
#define IDS_SET_THRESHOLD_FAILED        2092
#define IDS_TAB_INFO                    2093
#define IDS_TAB_CTRL                    2094
#define IDS_TAB_NOTE                    2095
#define IDS_TAB_LABEL                   2096
#define IDS_TAB_INHIBIT                 2097
#define IDS_TAB_OVERRIDE                2098
#define IDS_TAB_LIMIT                   2099
#define IDS_TAB_METER                   2100
#define IDS_TAB_STATUS                  2101
#define IDS_ADJUST_FAILED_MSG           2102
#define IDS_ADJUST_VALUE_FAILED_MSG     2103
#define IDS_ADJUST_SUCCESS              2104
#define IDS_NOTE_REMOVE_FAILED          2105
#define IDS_NOTE_REMOVE_FAILED_UNKNOWN  2106
#define IDS_NOTE_REMOVE_SUCCESS         2107
#define IDS_NOTE_ADD_FAILED             2108
#define IDS_NOTE_ADD_FAILED_UNKNOWN     2109
#define IDS_NOTE_ADD_SUCCESS            2110
#define IDS_OVERRIDE_COLUMN             2111
#define IDS_OVR_FAILED1                 2112
#define IDS_OVR_FAILED2                 2113
#define IDS_OVR_FAILED3                 2114
#define IDS_OVR_FAILED4                 2115
#define IDS_OVR_FAILED5                 2116
#define IDS_OVR_FAILED6                 2117
#define IDS_OVR_SUCCESSFUL1             2118
#define IDS_OVR_SUCCESSFUL2             2119
#define IDS_TAG_LAB1                    2120
#define IDS_TAG_LAB2                    2121
#define IDS_TAG_LAB3                    2122
#define IDS_TAG_LAB4                    2123
#define IDS_TAG_LAB5                    2124
#define IDS_TAG_LAB6                    2125
#define IDS_TAG_LAB7                    2126
#define IDS_TAG_LAB8                    2127
#define IDS_TAG_LAB9                    2128
#define IDS_TAG_LAB10                   2129
#define IDS_TAG_LAB11                   2130
#define IDS_TAG_LAB12                   2131
#define IDS_TAG_LAB13                   2132
#define IDS_TAG_LAB14                   2133
#define IDS_TAG_LAB15                   2134
#define IDS_TAG_LAB16                   2135
#define IDS_TAG_LAB17                   2136
#define IDS_TAG_LAB18                   2137
#define IDS_TAG_LAB19                   2138
#define IDS_TAG_LAB20                   2139
#define IDS_TAG_LAB21                   2140
#define IDS_TAG_LAB22                   2141
#define IDS_TAG_LAB23                   2142
#define IDS_ADJUST_COLUMN               2143
#define IDS_SCAN_COLUMN                 2144
#define IDS_ALARM_COLUMN                2145
#define IDS_OVERRIDE_VALUE_COLUMN       2146
#define IDS_UNDEFINED_STR               2147
#define IDS_LCC_FAILED_STR              2148
#define IDS_RCC_FAILED_STR              2149
#define IDS_COMMS_FAILED_STR            2150
#define IDS_CONTROL_SELECT_SENT_STR     2151
#define IDS_CONTROL_SELECT_CFR_STR      2152
#define IDS_CONTROL_EXE_SENT_STR        2153
#define IDS_CONTROL_EXE_CFM_STR         2154
#define IDS_CONTROL_CANCEL_SENT_STR     2155

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
