//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by step_plugin.decision_step.rc
//
#define IDS_STEP_PARAMETER_DECISION_MESSAGE 10001
#define IDS_STEP_PARAMETER_DECISION_RESPONSE_TIMEOUT 10002
#define IDS_STEP_PARAMETER_YES_STEP     10003
#define IDS_STEP_PARAMETER_NO_STEP      10004
#define IDS_STEP_PARAMETER_YES_LABEL    10005
#define IDS_STEP_PARAMETER_NO_LABEL     10006
#define IDS_STEP_PARAMETER_PAUSE_LABEL  10007
#define IDS_STEP_PARAMETER_NO_ENABLED   10008
#define IDS_STEP_PARAMETER_PAUSE_ENABLED 10009
#define IDS_DECISION_REPORT_COMPLETION_STATUS 10010
#define IDD_DECISION_DLG                11001
#define IDD_PLAN_STEP_EDIT_DECISION_DLG 11002
#define IDC_NO_STEP                     12001
#define IDC_DECISION_MESSAGE            12002
#define IDC_YES_STEP                    12003
#define IDC_YES_PICK_STEP_BUTTON        12004
#define IDC_NO_PICK_STEP_BUTTON         12005
#define IDC_YES_BUTTON_LABEL            12006
#define IDC_NO_BUTTON_LABEL             12007
#define IDC_PAUSE_BUTTON_LABEL          12008
#define IDC_NO_BUTTON_ENABLED           12009
#define IDC_PAUSE_BUTTON_ENABLED        12010
#define IDPAUSE                         12011
#define IDC_DECISION_PLAN_PATH_EDIT     12012
#define IDC_DECISION_ACTIVE_INSTANCE_EDIT 12013
#define IDC_DECISION_LOCATION_NAME_EDIT 12014
#define IDC_DECISION_STEP_NUMBER_EDIT   12015
#define IDC_DECISION_QUERY_EDIT         12016
#define IDC_DECISION_RESPONSE_TIMEOUT_SPIN 12017
#define IDC_DECISION_RESPONSE_TIMEOUT   12018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11003
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         12019
#define _APS_NEXT_SYMED_VALUE           10011
#endif
#endif
