//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoDisplayManager.rc
//
#define IDS_PROPSHT_CAPTION             2
#define IDD_VIDEODISPLAYMANAGER_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDB_QUADVMON                    135
#define IDB_QUADVMON_HILITE             136
#define IDI_CAMERA                      137
#define IDI_CLOSEDFOLDER                138
#define IDI_OPENFOLDER                  139
#define IDI_SEQUENCE                    140
#define IDI_QUAD                        141
#define IDC_DRAG_CURSOR                 148
#define IDD_CAMERAS                     149
#define IDD_QUADS                       150
#define IDD_SEQUENCES                   151
#define IDI_CAMERASELECTED              152
#define IDI_SEQUENCESELECTED            153
#define IDI_QUADSELECTED                154
#define IDR_MONCAMCONTEXT_MENU          155
#define IDD_SEQUENCEEDITOR_DIALOG       156
#define IDI_ADD                         157
#define IDI_REMOVE                      158
#define IDI_TOP                         159
#define IDI_UP                          160
#define IDI_DOWN                        161
#define IDI_BOTTOM                      162
#define IDD_RECORDINGUNIT_DIALOG        163
#define IDR_MAIN_MENU                   164
#define IDI_PLAY_ICON                   165
#define IDR_QUADCONTEXT_MENU            165
#define IDI_HALT_ICON                   166
#define IDI_PAUSE_ICON                  167
#define IDI_NEXTELEMENT_FF_ICON         168
#define IDI_RECORD_ICON                 169
#define IDI_PREVIOUSELEMENT_RW_ICON     170
#define IDD_SEQUENCECONTROLLER_DIALOG   171
#define IDD_QUADCONTROLLER_DIALOG       172
#define IDB_QUADSEG                     173
#define IDB_QUADSEG_HILITE              175
#define IDD_TRAINS                      177
#define IDI_TRAIN                       178
#define IDI_TRAINSELECTED               179
#define IDD_TRAINBORNECONTROLLER        181
#define IDB_QUADVMON_DISABLED           183
#define IDR_MONQUADCONTEXT_MENU         184
#define IDR_MONSEQCONTEXT_MENU          185
#define IDR_MONTRAINCONTEXT_MENU        186
#define IDR_VCRCONTEXT_MENU             187
#define IDR_PAGEQUADCONTEXT_MENU        188
#define IDR_PAGESEQCONTEXT_MENU         189
#define IDR_PAGETRAINCONTEXT_MENU       190
#define IDD_SAVEAS                      193
#define IDD_SAVEAS_DIALOG               193
#define IDR_MONALARMCONTEXT_MENU        194
#define IDD_DLG_INITPROGRESS            195
#define IDD_LOCATION_SELECTION          196
#define IDD_DLG_ALARM_TEST              197
#define IDC_SOURCES_TAB                 1001
#define IDC_COMMON_BOX                  1002
#define IDC_CONSOLE_BOX                 1003
#define IDC_WALL_MONITOR_1              1004
#define IDC_WALL_MONITOR_2              1005
#define IDC_WALL_MONITOR_3              1006
#define IDC_OVERVIEW_DISPLAY            1007
#define IDC_WALL_MONITOR_4              1008
#define IDC_WALL_MONITOR_5              1009
#define IDC_WALL_MONITOR_6              1010
#define IDC_CONSOLE_MONITOR_1           1011
#define IDC_CONSOLE_MONITOR_2           1012
#define IDC_CONSOLE_VCR_1               1013
#define IDC_CONSOLE_MONITOR_3           1013
#define IDC_CONSOLE_VCR_2               1014
#define IDC_LABEL_WALL_MONITOR_1        1015
#define IDC_LABEL_WALL_MONITOR_2        1016
#define IDC_LABEL_WALL_MONITOR_3        1017
#define IDC_LABEL_OVERVIEW_DISPLAY      1018
#define IDC_LABEL_WALL_MONITOR_4        1019
#define IDC_LABEL_WALL_MONITOR_5        1020
#define IDC_LABEL_WALL_MONITOR_6        1021
#define IDC_LABEL_CONSOLE_MONITOR_1     1022
#define IDC_LABEL_CONSOLE_MONITOR_2     1023
#define IDC_LABEL_CONSOLE_VCR_1         1024
#define IDC_LABEL_CONSOLE_MONITOR_3     1024
#define IDC_LABEL_CONSOLE_VCR_2         1025
#define IDC_CAMERATREE                  1026
#define IDC_QUADTREE                    1027
#define IDC_SEQUENCETREE                1028
#define IDC_TEXT_WALL_MONITOR_1         1029
#define IDC_TEXT_WALL_MONITOR_2         1030
#define IDC_TEXT_WALL_MONITOR_3         1031
#define IDC_TEXT_OVERVIEW_DISPLAY       1032
#define IDC_TEXT_WALL_MONITOR_4         1033
#define IDC_TEXT_WALL_MONITOR_5         1034
#define IDC_TEXT_WALL_MONITOR_6         1035
#define IDC_TEXT_CONSOLE_MONITOR_1      1036
#define IDC_TEXT_CONSOLE_MONITOR_2      1037
#define IDC_SE_DESCRIPTION_EDIT_BOX     1038
#define IDC_TEXT_CONSOLE_MONITOR_3      1038
#define IDC_SE_DWELLTIME_LABEL          1039
#define IDC_SE_SEQUENCE_LABEL           1040
#define IDC_SE_DWELLTIME_EDIT_BOX       1041
#define IDC_SE_DESCRIPTION_LABEL        1042
#define IDC_SE_ADD_BUTTON               1043
#define IDC_SE_REMOVE_BUTTON            1044
#define IDC_SE_SOURCES_INSEQUENCE_LABEL 1045
#define IDC_SE_SEQUENCES_LIST           1046
#define IDC_SE_TOP_BUTTON               1047
#define IDC_SE_UP_BUTTON                1048
#define IDC_SE_DOWN_BUTTON              1049
#define IDC_SE_BOTTOM_BUTTON            1050
#define IDC_SE_SECONDS_LABEL            1051
#define IDC_SE_SAVE_BUTTON              1052
#define IDC_SE_CAMERATREE               1053
#define ID_SE_AVAILABLECAMERAS_LABEL    1054
#define IDC_TABMARKER                   1055
#define IDC_RU_RECORDINGUNIT_EDIT       1056
#define IDC_RU_MONITOR_EDIT             1057
#define IDC_RU_PLAY_CHECK               1059
#define IDC_MENU_LINE                   1061
#define IDC_SC_SEQNAMEDESCRIPTION_EDIT  1063
#define IDC_SC_MONITOR_EDIT             1064
#define IDC_SC_HALT_BUTTON              1065
#define IDC_SC_PREVIOUSELEMENT_BUTTON   1066
#define IDC_SC_PLAY_CHECK               1067
#define IDC_SC_NEXTELEMENT_BUTTON       1068
#define IDC_SC_PAUSE_CHECK              1069
#define IDC_RU_RECORD_CHECK             1070
#define IDC_RU_REWIND_CHECK             1071
#define IDC_RU_STOP_CHECK               1072
#define IDC_RU_FAST_FORWARD_CHECK       1073
#define IDC_RU_PAUSE_CHECK              1074
#define IDC_QC_CAMERATREE               1075
#define IDC_QC_APPLY_BUTTON             1076
#define IDC_QC_QUAD_LABEL               1077
#define IDC_QUADSEG1                    1078
#define IDC_QUADSEG2                    1079
#define IDC_QUADSEG3                    1080
#define IDC_QUADSEG4                    1081
#define IDC_TEXT_QUADSEG_1              1082
#define IDC_TEXT_QUADSEG_2              1083
#define IDC_TEXT_QUADSEG_3              1084
#define IDC_TEXT_QUADSEG_4              1085
#define ID_QC_AVAILABLECAMERAS_LABEL    1086
#define IDC_SEQUENCENAMEDESC_EDIT       1087
#define IDC_TRAINSLIST                  1088
#define IDC_TRAINSLIST_IB               1088
#define IDC_TC_TRAIN_LABEL              1089
#define IDC_TRAINCAR1                   1090
#define IDC_TRAINSLIST_OB               1090
#define IDC_TRAINCAR2                   1091
#define IDC_TRAINCAR3                   1092
#define IDC_QUADRADIO                   1095
#define IDC_SINGLERADIO                 1096
#define IDC_SEQUENCERADIO               1097
#define IDC_SEQUENCECOMBO               1098
#define IDC_TRAINSINGLEMON              1099
#define IDC_TRAINQUADMON1               1100
#define IDC_TRAINQUADMON2               1101
#define IDC_TRAINQUADMON3               1102
#define IDC_TRAINQUADMON4               1103
#define IDC_TC_APPLY_BUTTON             1105
#define IDC_TRAINCAM1                   1106
#define IDC_TRAINCAM2                   1107
#define IDC_TRAINCAM3                   1108
#define IDC_TRAINCAM4                   1109
#define IDC_TRAINCAM5                   1110
#define IDC_TRAINCAM6                   1111
#define IDC_TRAINCAM7                   1112
#define IDC_TRAINCAM8                   1113
#define IDC_CAM1_LABEL                  1114
#define IDC_CAM2_LABEL                  1115
#define IDC_SPIN1                       1115
#define IDC_DWELLTIME_SPIN              1115
#define IDC_CAM3_LABEL                  1116
#define IDC_DETAILS_EDIT                1116
#define IDC_CAM4_LABEL                  1117
#define IDC_DETAILS_BOX                 1117
#define IDC_CAM5_LABEL                  1118
#define IDC_TEST                        1118
#define IDC_CAM6_LABEL                  1119
#define IDC_COMMON_PREVIOUSELEMENT_BUTTON 1119
#define IDC_CAM7_LABEL                  1120
#define IDC_COMMON_PLAY_CHECK           1120
#define IDC_CAM8_LABEL                  1121
#define IDC_COMMON_NEXTELEMENT_BUTTON   1121
#define IDC_SINGLEMON_TEXT              1122
#define IDC_COMMON_PAUSE_CHECK          1122
#define IDC_QUAD1_TEXT                  1123
#define IDC_QUAD2_TEXT                  1124
#define IDC_COMMON_PLAYBACK_LABEL       1124
#define IDC_QUAD3_TEXT                  1125
#define IDC_CONSOLE_PLAYBACK_LABEL      1125
#define IDC_QUAD4_TEXT                  1126
#define IDC_SAVEAS_SEQUENCETREE         1126
#define IDC_CONSOLE_PREVIOUSELEMENT_BUTTON 1127
#define IDC_CONSOLE_PLAY_CHECK          1128
#define IDC_CONSOLE_NEXTELEMENT_BUTTON  1129
#define IDC_CONSOLE_PAUSE_CHECK         1130
#define IDC_PROGRESS_CTRL               1131
#define IDC_STATIC_TEXT1                1132
#define IDC_STATIC_TEXT2                1133
#define IDC_STATIC_TEXT3                1134
#define IDC_LOCSEL_COMBOBOX_LOCATIONS   1135
#define IDC_HOTKEY1                     1136
#define IDC_VD_OCC_DETAILS_EDIT         1137
#define IDC_VD_OCC_TABMARKER            1138
#define IDC_VD_OCC_TAB_VIDEOINPUT       1140
#define IDC_ALARMTEST_ED_ALARMKEY       1143
#define IDC_ALARMTEST_ED_STATIONID      1144
#define IDC_ALARMTEST_ED_EVENTID        1145
#define IDC_BUTTON1                     1146
#define IDC_ALARMTEST_BU_ACKNOWLDGE_ALARM 1146
#define IDC_ALARMTEST_BU_CLOSE_ALARM    1147
#define IDC_ALARMTEST_ED_RUNPARAM_NAME  1148
#define IDC_ALARMTEST_ED_RUN_PARAM_VALUE 1149
#define IDC_ALARMTEST_ED_RUNPARAM_VALUE 1149
#define IDC_VD_PSC_DETAILS_EDIT         1150
#define IDC_ALARMTEST_BU_RUNPARAM_CHANGE 1150
#define IDC_VD_PSC_TAB_VIDEOINPUT       1151
#define IDC_ALARMTEST_ED_TRIGGERING_ALARMLIST 1151
#define IDC_VD_KOCC_TAB_VIDEOINPUT      1152
#define IDC_ALARMTEST_BU_PROCESS_TRIGGERING_ALARM 1152
#define IDC_VD_TMF_TAB_VIDEOINPUT       1153
#define IDC_VD_TMF_CONSOLE_MON_2        1154
#define IDC_VD_TMF_CONSOLE_MON_1        1155
#define IDC_VD_TMF_DETAILS_EDIT         1156
#define IDC_VD_TMF_CONSOLE_MON_TEXT_1   1157
#define IDC_VD_TMF_CONSOLE_MON_TEXT_2   1158
#define IDC_VD_GBD_OVERALL_MON_1        1159
#define IDC_VD_GBD_CONSOLE_MON_1        1160
#define IDC_VD_GBD_CONSOLE_MON_2        1161
#define IDC_VD_GBD_TAB_VIDEOINPUT       1162
#define IDC_VD_GBD_DETAILS_EDIT         1163
#define IDC_VD_GBD_OVERALL_MON_TEXT_1   1164
#define IDC_VD_GBD_CONSOLE_MON_TEXT_1   1165
#define IDC_VD_GBD_CONSOLE_MON_TEXT_2   1166
#define IDC_VD_TDS_TAB_VIDEOINPUT       1167
#define IDC_VD_TDS_CONSOLE_MON_1        1168
#define IDC_VD_TDS_DETAILS_EDIT         1169
#define IDC_VD_TDS_CONSOLE_MON_TEXT_1   1170
#define IDC_CHECK1                      1171
#define IDC_ALARMTEST_CH_OPEN_TRIGGERINGALARM 1171
#define IDB_VD_OVERALL                  2001
#define IDB_VD_OVERALL_H                2002
#define IDB_VD_WALL                     2003
#define IDB_VD_WALL_H                   2004
#define IDB_VD_CONSOLE                  2005
#define IDB_VD_CONSOLE_H                2006
#define IDB_VD_WALL_SMALL               2007
#define IDB_VD_WALL_SMALL_H             2008
#define IDC_VD_OCC_OVERALL_MON_1        2025
#define IDC_VD_OCC_OVERALL_MON_TEXT_1   2026
#define IDC_VD_OCC_CONSOLE_MON_1        2027
#define IDC_VD_OCC_CONSOLE_MON_TEXT_1   2028
#define IDC_VD_KOCC_LT_DETAILS          2048
#define IDC_VD_KOCC_DETAILS_EDIT        2048
#define IDC_VD_KOCC_WALL_MON_1          2049
#define IDC_VD_DPT_LT_DETAILS           2049
#define IDC_VD_KOCC_WALL_MON_2          2050
#define IDC_VD_KOCC_WALL_MON_3          2051
#define IDC_VD_KOCC_WALL_MON_4          2052
#define IDC_VD_KOCC_OVERALL_MON_1       2053
#define IDC_VD_KOCC_CONSOLE_MON_1       2054
#define IDC_VD_KOCC_WALL_MON_TEXT_1     2056
#define IDC_VD_KOCC_WALL_MON_TEXT_2     2057
#define IDC_VD_KOCC_WALL_MON_TEXT_3     2058
#define IDC_VD_KOCC_WALL_MON_TEXT_4     2059
#define IDC_VD_KOCC_OVERALL_MON_TEXT_1  2060
#define IDC_VD_KOCC_CONSOLE_MON_TEXT_1  2061
#define IDC_VD_PSC_LT_DETAILS           2062
#define IDC_VD_PSC_CONSOLE_MON_TEXT_1   2063
#define IDC_VD_PSC_CONSOLE_MON_TEXT_2   2064
#define IDC_VD_PSC_CONSOLE_MON_1        2065
#define IDC_VD_PSC_CONSOLE_MON_2        2066
#define IDC_VD_PSC_CONSOLE_MON_3        2067
#define IDC_VD_PSC_CONSOLE_MON_TEXT_3   2068
#define IDC_VD_OCC_WALL_MON_1           2070
#define IDC_VD_OCC_WALL_MON_2           2071
#define IDC_VD_OCC_WALL_MON_3           2072
#define IDC_VD_OCC_WALL_MON_4           2073
#define IDC_VD_OCC_WALL_MON_5           2074
#define IDC_VD_OCC_WALL_MON_6           2075
#define IDC_VD_OCC_WALL_MON_7           2076
#define IDC_VD_OCC_WALL_MON_8           2077
#define IDC_VD_OCC_WALL_MON_9           2078
#define IDC_VD_OCC_WALL_MON_10          2079
#define IDC_VD_OCC_WALL_MON_11          2080
#define IDC_VD_OCC_WALL_MON_12          2081
#define IDC_VD_OCC_WALL_MON_13          2082
#define IDC_VD_OCC_WALL_MON_14          2083
#define IDC_VD_OCC_WALL_MON_15          2084
#define IDC_VD_OCC_WALL_MON_16          2085
#define IDC_VD_OCC_WALL_MON_17          2086
#define IDC_VD_OCC_WALL_MON_18          2087

#define IDC_VD_OCC_WALL_MON_TEXT_1      2090
#define IDC_VD_OCC_WALL_MON_TEXT_2      2091
#define IDC_VD_OCC_WALL_MON_TEXT_3      2092
#define IDC_VD_OCC_WALL_MON_TEXT_4      2093
#define IDC_VD_OCC_WALL_MON_TEXT_5      2094
#define IDC_VD_OCC_WALL_MON_TEXT_6      2095
#define IDC_VD_OCC_WALL_MON_TEXT_7      2096
#define IDC_VD_OCC_WALL_MON_TEXT_8      2097
#define IDC_VD_OCC_WALL_MON_TEXT_9      2098
#define IDC_VD_OCC_WALL_MON_TEXT_10     2099
#define IDC_VD_OCC_WALL_MON_TEXT_11     2100
#define IDC_VD_OCC_WALL_MON_TEXT_12     2101
#define IDC_VD_OCC_WALL_MON_TEXT_13     2102
#define IDC_VD_OCC_WALL_MON_TEXT_14     2103
#define IDC_VD_OCC_WALL_MON_TEXT_15     2104
#define IDC_VD_OCC_WALL_MON_TEXT_16     2105
#define IDC_VD_OCC_WALL_MON_TEXT_17     2106
#define IDC_VD_OCC_WALL_MON_TEXT_18     2107

#define IDD_VIDEODISPLAYMANAGER_DIALOG_OCC 4000
#define IDD_VIDEODISPLAYMANAGER_DIALOG_KOCC 4016
#define IDD_VIDEODISPLAYMANAGER_DIALOG_PSC 4017
#define IDD_VIDEODISPLAYMANAGER_DIALOG_TMF 4018
#define IDD_VIDEODISPLAYMANAGER_DIALOG_GBD 4019
#define IDD_VIDEODISPLAYMANAGER_DIALOG_TDS 4020
#define ID_LOAD_CONTROLLER              32771
#define ID_CLEAR_MONITOR                32772
#define ID_NEW_EDIT_SEQUENCE            32773
#define ID_DEACTIVATE_TRAIN             32774
#define ID_APP_HELP                     32775
#define ID_TIMELAPSE_MODE               32776
#define ID_REALTIME_MODE                32777
#define IDS_UE010016_CANNOT_LOAD_DATA   57665

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
