//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoDisplayManager.rc
//
#define IDS_PROPSHT_CAPTION             2
#define ID_BTN_PLAYBACK_HELP            3
#define ID_BTN_PLAYBACK_REWIND          4
#define ID_BTN_PLAYBACK_PLAY            5
#define ID_BTN_PLAYBACK_STOP            6
#define ID_BTN_PLAYBACK_FORWARD         7
#define IDD_VIDEODISPLAYMANAGER_DIALOG  102
#define IDD_QCAPDLG                     106
#define IDR_MAINFRAME                   128
#define IDB_TRAINCAMRIGHT               129
#define IDB_TRAINCAMLEFT                130
#define IDB_TRAINCAMRIGHT_HILITE        131
#define IDB_TRAINCAMLEFT_HILITE         132
#define IDB_VMON_HILITE                 133
#define IDB_VMON                        134
#define IDB_QUADVMON                    135
#define IDB_QUADVMON_HILITE             136
#define IDI_CAMERA                      137
#define IDI_CLOSEDFOLDER                138
#define IDI_OPENFOLDER                  139
#define IDI_SEQUENCE                    140
#define IDI_QUAD                        141
#define IDB_VCR                         142
#define IDB_VCR_HILITE                  143
#define IDB_SINGLEVMON                  144
#define IDB_SINGLEVMON_HILITE           145
#define IDB_ODS                         146
#define IDB_ODS_HILITE                  147
#define IDC_DRAG_CURSOR                 148
#define IDD_CAMERAS                     149
#define IDD_QUADS                       150
#define IDD_SEQUENCES                   151
#define IDR_MONCAMCONTEXT_MENU          155
#define IDD_SEQUENCEEDITOR_DIALOG       156
#define IDI_ADD                         157
#define IDI_REMOVE                      158
#define IDI_TOP                         159
#define IDI_UP                          160
#define IDI_DOWN                        161
#define IDI_BOTTOM                      162
#define IDD_RECORDINGUNIT_DIALOG        163
#define IDR_MAIN_MENU                   164
#define IDI_PLAY_ICON                   165
#define IDR_QUADCONTEXT_MENU            165
#define IDI_HALT_ICON                   166
#define IDI_PAUSE_ICON                  167
#define IDI_NEXTELEMENT_FF_ICON         168
#define IDI_RECORD_ICON                 169
#define IDI_PREVIOUSELEMENT_RW_ICON     170
#define IDD_QUADCONTROLLER_DIALOG       172
#define IDB_QUADSEG                     173
#define IDB_QUADSEG_HILITE              175
#define IDD_TRAINS                      177
#define IDI_TRAIN                       178
#define IDD_TRAINBORNECONTROLLER        181
#define IDB_SINGLEVMON_DISABLED         182
#define IDB_QUADVMON_DISABLED           183
#define IDR_MONQUADCONTEXT_MENU         184
#define IDR_MONSEQCONTEXT_MENU          185
#define IDR_MONTRAINCONTEXT_MENU        186
#define IDR_VCRCONTEXT_MENU             187
#define IDR_PAGEQUADCONTEXT_MENU        188
#define IDR_PAGESEQCONTEXT_MENU         189
#define IDR_PAGETRAINCONTEXT_MENU       190
#define IDB_SINGLEVMON_FORTRAIN         191
#define IDB_SINGLEVMON_FORTRAIN_HILITE  192
#define IDD_SAVEAS_DIALOG               193
#define IDR_MONALARMCONTEXT_MENU        194
#define IDD_DLG_INITPROGRESS            195
#define IDD_LOCATION_SELECTION          196
#define IDD_STATIONDISPLAY_DIALOG       197
#define IDI_ZOOM_OUT                    203
#define IDI_EAST_ARROW                  204
#define IDI_WEST_ARROW                  205
#define IDI_NORTH_ARROW                 206
#define IDI_SOUTH_ARROW                 207
#define IDI_ZOOM_IN                     208
#define IDI_PT_NW_ICON                  210
#define IDI_PT_NE_ICON                  213
#define IDI_PT_SE_ICON                  214
#define IDI_PT_SW_ICON                  215
#define IDI_ZOOM_IN_ICON                216
#define IDI_ZOOM_OUT_ICON               218
#define IDD_VIDEO_PLAY                  220
#define IDR_VIDEO_CONTROL               221
#define IDD_TEST_DLG                    222
#define IDI_UNKNOW                      225
#define IDI_BACKUP                      226
#define IDI_UNLOCK                      227
#define IDD_PLAY_BACK_DLG               245
#define IDD_DLG_PLAYBACK_SET            247
#define IDB_SINGLEVMON_HIGHLIGTH_DIV_4  250
#define IDB_SINGLEVMON_DIV_4            251
#define IDC_VIDEO                       252
#define IDB_SINGLEODS                   253
#define IDB_SINGLEODS_HILITE            254
#define IDB_SINGLEODS_HILITE_DIV_4      256
#define IDB_SINGLEODS_DIV_4             257
#define IDC_COMMON_BOX                  1002
#define IDC_QUAD1                       1007
#define IDC_CONSOLE_MONITOR_1           1011
#define IDC_QUAD3                       1012
#define IDC_QUAD2                       1013
#define IDC_QUAD4                       1014
#define IDC_LOCAL_MONITOR               1015
#define IDC_VD_OCC_WALL_MON_1           1015
#define IDC_LABEL_OVERVIEW_DISPLAY      1018
#define IDC_CAMERATREE                  1026
#define IDC_QUADTREE                    1027
#define IDC_SEQUENCETREE                1028
#define IDC_TEXT_CONSOLE_MONITOR_2      1037
#define IDC_SE_DESCRIPTION_EDIT_BOX     1038
#define IDC_SE_DWELLTIME_LABEL          1039
#define IDC_SE_DWELLTIME_EDIT_BOX       1041
#define IDC_SE_DESCRIPTION_LABEL        1042
#define IDC_SE_ADD_BUTTON               1043
#define IDC_SE_REMOVE_BUTTON            1044
#define IDC_SE_SOURCES_INSEQUENCE_LABEL 1045
#define IDC_SE_SEQUENCES_LIST           1046
#define IDC_SE_TOP_BUTTON               1047
#define IDC_SE_UP_BUTTON                1048
#define IDC_SE_DOWN_BUTTON              1049
#define IDC_SE_BOTTOM_BUTTON            1050
#define IDC_SE_SECONDS_LABEL            1051
#define IDC_SE_SAVE_BUTTON              1052
#define IDC_SE_CAMERATREE               1053
#define ID_SE_AVAILABLECAMERAS_LABEL    1054
#define IDC_RU_RECORDINGUNIT_EDIT       1056
#define IDC_RU_MONITOR_EDIT             1057
#define IDC_RU_PLAY_CHECK               1059
#define IDC_MENU_LINE                   1061
#define IDC_RU_RECORD_CHECK             1070
#define IDC_RU_REWIND_CHECK             1071
#define IDC_RU_STOP_CHECK               1072
#define IDC_RU_FAST_FORWARD_CHECK       1073
#define IDC_RU_PAUSE_CHECK              1074
#define IDC_QC_CAMERATREE               1075
#define IDC_QC_APPLY_BUTTON             1076
#define IDC_QUADSEG1                    1078
#define IDC_QUADSEG2                    1079
#define IDC_QUADSEG3                    1080
#define IDC_QUADSEG4                    1081
#define IDC_TEXT_QUADSEG_1              1082
#define IDC_TEXT_QUADSEG_2              1083
#define IDC_TEXT_QUADSEG_3              1084
#define IDC_TEXT_QUADSEG_4              1085
#define ID_QC_AVAILABLECAMERAS_LABEL    1086
#define IDC_SEQUENCENAMEDESC_EDIT       1087
#define IDC_TRAINSLIST_IB               1088
#define IDC_TC_TRAIN_LABEL              1089
#define IDC_TRAINCAR1                   1090
#define IDC_TRAINSLIST_OB               1090
#define IDC_TRAINCAR2                   1091
#define IDC_TRAINCAR3                   1092
#define IDC_QUADRADIO                   1095
#define IDC_SINGLERADIO                 1096
#define IDC_SEQUENCERADIO               1097
#define IDC_SEQUENCECOMBO               1098
#define IDC_TRAINSINGLEMON              1099
#define IDC_TRAINQUADMON1               1100
#define IDC_TRAINQUADMON2               1101
#define IDC_TRAINQUADMON3               1102
#define IDC_TRAINQUADMON4               1103
#define IDC_TC_APPLY_BUTTON             1105
#define IDC_TRAINCAM1                   1106
#define IDC_TRAINCAM2                   1107
#define IDC_TRAINCAM3                   1108
#define IDC_TRAINCAM4                   1109
#define IDC_TRAINCAM5                   1110
#define IDC_TRAINCAM6                   1111
#define IDC_TRAINCAM7                   1112
#define IDC_TRAINCAM8                   1113
#define IDC_CAM1_LABEL                  1114
#define IDC_CAM2_LABEL                  1115
#define IDC_DWELLTIME_SPIN              1115
#define IDC_CAM3_LABEL                  1116
#define IDC_CAM4_LABEL                  1117
#define IDC_CAM5_LABEL                  1118
#define IDC_CAM6_LABEL                  1119
#define IDC_CAM7_LABEL                  1120
#define IDC_CAM8_LABEL                  1121
#define IDC_SINGLEMON_TEXT              1122
#define IDC_QUAD1_TEXT                  1123
#define IDC_QUAD2_TEXT                  1124
#define IDC_QUAD3_TEXT                  1125
#define IDC_QUAD4_TEXT                  1126
#define IDC_SAVEAS_SEQUENCETREE         1126
#define IDC_PROGRESS_CTRL               1131
#define IDC_STATIC_TEXT1                1132
#define IDC_STATIC_TEXT2                1133
#define IDC_STATIC_TEXT3                1134
#define IDC_LOCSEL_COMBOBOX_LOCATIONS   1135
#define IDC_GF_SEQUENCE_OCC             1145
#define IDC_STATION_MONITOR_GROUP       1146
#define IDC_GF_OCC_SEQ_STATION_COMB     1147
#define IDC_GF_SEQENCE_TREE             1148
#define IDC_GF_OCC_SEL_STATION_COMB     1149
#define IDC_GF_EDIT_SEQ_BTN             1150
#define IDC_GF_SEQ_LST                  1151
#define IDC_STATION_SEQUENCE_GROUP      1152
#define IDC_GF_OCC_STATION_PIC          1153
#define IDC_STATION_SEQ_STATION_COMB    1154
#define IDC_STATION_SEQENCE_TREE        1155
#define IDC_STATION_EDIT_SEQ_BTN        1156
#define IDC_STATION_SEQ_LST             1157
#define IDC_STATION_PTZ_GROUP           1158
#define IDC_STATION_SEL_STATION_COMB    1159
#define IDC_STATION_STATION_PIC         1160
#define IDC_STATION_PIC_GROUP           1161
#define IDC_PT_LEFT_UP_BTN              1162
#define IDC_TILT_UP_BTN                 1163
#define IDC_PT_RIGHT_UP_BTN             1164
#define IDC_PAN_RIGHT_BTN               1165
#define IDC_PT_RIGHT_DOWN_BTN           1166
#define IDC_TILT_DOWN_BTN               1167
#define IDC_PT_LEFT_DOWN_BTN            1168
#define IDC_PAN_LEFT_BTN                1169
#define IDC_ZOOM_OUT_BTN                1170
#define IDC_ZOOM_IN_BTN                 1171
#define IDC_STATIC_QUAD                 1172
#define IDC_LOCAL_MONITOR_TEXT          1173
#define IDC_QUAD1_INDEX                 1179
#define IDC_QUAD2_INDEX                 1180
#define IDC_QUAD3_INDEX                 1181
#define IDC_QUAD4_INDEX                 1182
#define IDC_OPC_MONITOR_DESC            1184
#define IDC_OPC_MONITOR_DESC2           1185
#define IDC_BUTTON_ACK_ALARM            1189
#define IDC_DOWN_PLT_BTN                1200
#define IDC_B1_BTN                      1201
#define IDC_B2_BTN                      1202
#define IDC_PARAM_NAME                  1204
#define IDC_PARAM_VALUE                 1205
#define IDC_PARAM_AND_VALUE             1206
#define IDB_PAUSE_BITMAP                1207
#define IDC_PLAYBACK_START_DATE         1208
#define IDB_PLAY_BITMAP                 1209
#define IDC_PLAYBACK_END_DATE           1210
#define IDB_REWIND_BITMAP               1211
#define IDC_PLAYBACK_START_TIME         1212
#define IDB_FORWARD_BITMAP              1213
#define IDC_PLAYBACK_STOP_TIME          1214
#define IDB_STOP_BITMAP                 1215
#define IDC_PLAYBACK_VIDEO_WINDOW       1216
#define IDC_EDIT_ALARM_ENTITYKEY_ACK    1217
#define IDC_STATIC_PLAY                 1218
#define IDC_EDIT_ALARM_ENTITYKEY_SUBMIT 1219
#define IDC_BUTTON_SUBMIT_ALARM         1220
#define IDC_WALLMONITOR_PLACEHOLDER     1222
#define IDC_OCC_SCHEMATIC_SEL_LIST      1223
#define IDC_STATION_SCHEMATIC_SEL_LIST  1224
#define ID_LOAD_CONTROLLER              32771
#define ID_CLEAR_MONITOR                32772
#define ID_NEW_EDIT_SEQUENCE            32773
#define ID_DEACTIVATE_TRAIN             32774
#define ID_APP_HELP                     32775
#define ID_TIMELAPSE_MODE               32776
#define ID_REALTIME_MODE                32777
#define ID_VIDEO_CONTROL_STOP           32782
#define IDS_UE010016_CANNOT_LOAD_DATA   57665

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1225
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
