/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/pa/PAAgent/src/AbstractPASTable.cpp $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2008/11/28 16:26:01 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//
//  AbstractPASTable.cpp
//  Implementation of the Class AbstractPASTable
//  Generated by Enterprise Architect
//  Created on:      25-Sep-2003 18:53:34
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#if defined(_MSC_VER)
#pragma warning(disable : 4786 4146 4018 4250 4290)
#endif // defined _MSC_VER

#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtil.h"

#include "app/pa/PAAgent/src/AbstractPASTable.h"

#include <string.h>

AbstractPASTable::AbstractPASTable(unsigned long tableNumber,
                                   unsigned int bufferSize)
    : TABLE_NUMBER(tableNumber)
    , BUFFER_SIZE(bufferSize)
    , m_lock()
    , m_buffer( new ta_uint8[bufferSize] )
{
    TA_ASSERT(tableNumber!=0, "AbstractPASTable has not been initialised from concrete table instance");
    memset( m_buffer, 0, bufferSize );
}

