/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_TIP/4669/transactive/app/radio/RadioTetraAgent/RadioProtocolLibrary/src/RadioMethod.h $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2008/10/31 12:15:01 $
  * Last modified by:  $Author: grace.koh $
  *
  */
///////////////////////////////////////////////////////////
//
//  RadioMethod.h
//  Implementation of the Class RadioMethod
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2003 08:32:16
//  Original author: Andy Parker
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(RadioMethod_96770BC0_1AF8_4f8c_BDA3_FB5486E2BD8E__INCLUDED_)
#define RadioMethod_96770BC0_1AF8_4f8c_BDA3_FB5486E2BD8E__INCLUDED_

#include <string>
#include "app/radio/RadioTetraAgent/RadioMethodProtocol/src//ITcpMethod.h"


/**
* This class encapulates the data associated with a radio method.
* @author Andy Parker
* @version 1.0
* @generator Enterprise Architect
* @created 06-Nov-2003 08:32:15
*/

namespace TA_IRS_App
{
	class RadioMethod : public ITcpMethod
	{

		protected:

			RadioMethod(unsigned int methodLength, unsigned char methodStx);

		public:
			virtual ~RadioMethod();


			void setTransactionId(unsigned long transactionId);
			/**
			* Return the timestamp
			*/
			std::string getTimestamp();
			/**
			* Return the specified length of the message header
			*/
			virtual unsigned long getMethodHeaderLength() const;
			/**
			* Set the specified length of the message header
			*/
			virtual void setMethodHeaderLength(unsigned int messageSize);
			/**
			* Return the specified length of the message header
			*/
			virtual unsigned long getShortStringLength() const;


		private:


			/*
			* Disable the assignment and copy constructors
			*/
			RadioMethod& operator=(const RadioMethod &);
			RadioMethod( const RadioMethod& radioMethod); 
		
	};
};

#endif // !defined(RadioMethod_96770BC0_1AF8_4f8c_BDA3_FB5486E2BD8E__INCLUDED_)
