/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/RadioProtocolLibrary/src/RadioMethodAttachSession.h $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2008/11/28 16:26:01 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//
//  RadioMethodAttachSession.h
//  Implementation of the Class RadioMethodAttachSession
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2003 09:58:38
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(RadioMethodAttachSession_2DDF887C_7234_4da4_ABB6_32EBD1F3FFD9__INCLUDED_)
#define RadioMethodAttachSession_2DDF887C_7234_4da4_ABB6_32EBD1F3FFD9__INCLUDED_

#include "RadioMethod.h"

/**
* Create a new session with the radio hardware
* @version 1.0
* @generator Enterprise Architect
* @created 06-Nov-2003 09:58:38
*/

namespace TA_IRS_App
{
	class RadioMethodAttachSession : public RadioMethod
	{

		public:
			/**
			* Constructor
			* @param    sessionRef
			*/
			RadioMethodAttachSession();
			virtual ~RadioMethodAttachSession();

		public:
	};
};

#endif // !defined(RadioMethodAttachSession_2DDF887C_7234_4da4_ABB6_32EBD1F3FFD9__INCLUDED_)
