//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by step_plugin.station_pa_step.rc
//
#define IDD_PA_STATION_ZONES_DLG        26420
#define IDD_PLAN_STEP_PA_STATION_DLG    26421
#define IDD_STATIONPA_PA_STATION_MESSAGE_DLG      26422
#define IDC_STATIONPA_TIS_SYNCH_CHECK             26431
#define IDC_STATIONPA_CYCLIC_CHECK                26432
#define IDC_STATIONPA_ALL_PA_STATIONS_RADIO       26433
#define IDC_STATIONPA_CHIME_CHECK                 26434
#define IDC_STATIONPA_STATIONS_COMBO              26435
#define IDC_STATIONPA_PA_STATION_RADIO            26436
#define IDC_STATIONPA_DURATION_DTPICKER           26437
#define IDC_STATIONPA_INTERVAL_TXT                26438
#define IDC_STATIONPA_MESSAGE_TXT                 26440
#define IDC_STATIONPA_MSG_DLG_BTN                 26441
#define IDC_STATIONPA_ZONE_LIST                   26442
#define IDC_STATIONPA_ZONE_DLG__BTN               26443
#define IDC_STATIONPA_AVAILABLE_ZONES_LIST        26444
#define IDC_STATIONPA_SELECTED_ZONES_LIST         26445
#define IDC_STATIONPA_SELECT_BTN                  26446
#define IDC_STATIONPA_UNSELECT_BTN                26447
#define IDC_STATIONPA_ZONE_GROUPS_COMBO           26448
#define IDC_STATIONPA_STATION_NAME_TXT            26449
#define IDC_STATIONPA_SELECT_ALL_BTN              26450
#define IDC_STATIONPA_UNSELECT_ALL_BTN            26451
#define IDC_STATIONPA_PARAMETER_NAME_TXT          26452
#define IDC_STATIONPA_LIB_SECTION_TXT             26453
#define IDC_STATIONPA_LIB_VERSION_TXT             26454
#define IDC_STATIONPA_MESSAGES_LIST               26455
#define IDS_STATIONPA_STEP_PARAMETER_PA_STATION   26460
#define IDS_STATIONPA_STEP_PARAMETER_PA_DURATION  26461
#define IDS_STATIONPA_STEP_PARAMETER_PA_ZONE      26462
#define IDS_STATIONPA_STEP_PARAMETER_PA_INTERVAL  26463
#define IDS_STATIONPA_STEP_PARAMETER_PA_CHIME     26464
#define IDS_STATIONPA_STEP_PARAMETER_PA_CYCLIC    26465
#define IDS_STATIONPA_STEP_PARAMETER_PA_TIS_SYNCH 26466
#define IDS_STATIONPA_STEP_PARAMETER_PA_MESSAGE   26467

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        27000
#define _APS_NEXT_COMMAND_VALUE         27001
#define _APS_NEXT_CONTROL_VALUE         27003
#define _APS_NEXT_SYMED_VALUE           27003
#endif
#endif
