//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TrainBorneManager.rc
//
#define IDC_BUTTON_HLP                  3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TrainBorneTEST_DIALOG       102
#define IDD_TRAINBORNEMANAGER_DIALOG    102
#define IDD_TISMANAGER_DIALOG           102
#define IDD_TRAINCONTROLMANAGER_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDD_STATION_DISPLAY             129
#define IDD_TRAIN_DISPLAY               130
#define IDD_TRAIN_TIME_SCHEDULE         131
#define IDR_MENU1                       132
#define IDD_TRAIN_DOWNLOAD              133
#define IDD_SELECT_PREDEFINED           134
#define IDD_TRAIN_DETAIL_TEST           135
#define IDD_STATION_SELECT_FREETEXT     135
#define IDD_STATION_PLASMA_ATTRIBUTES   136
#define IDD_STATION_LED_ATTRIBUTES      137
#define IDD_LIBRARY_DOWNLOAD            138
#define IDD_SCHEDULE_DOWNLOAD           139
#define IDD_TRAIN_SELECT_FREETEXT       141
#define IDD_SELECT_PID_GROUP            142
#define IDD_STATION_SELECT_PREDEFINED   143
#define IDD_TRAIN_SELECT_PREDEFINED     145
#define IDD_EDIT_FREE_TEXT              146
#define IDR_TOOLBAR1                    147
#define IDD_STATION_BROADCAST           154
#define IDD_SCROLLY_DLG                 156
#define IDD_SCROLLEDNUMBER_DLG          156
#define IDD_DVA_VERSIONS                163
#define IDD_PAMANAGER_DIALOG            164
#define IDD_MAIN_DLG                    168
#define IDB_RECORD_BITMAP               176
#define IDB_PLAY_BITMAP                 177
#define IDB_STOP_BITMAP                 178
#define IDB_STNMUSIC_BITMAP             183
#define IDB_OCCMUSIC_BITMAP             184
#define IDB_DVA_BITMAP                  185
#define IDB_LIVE_BITMAP                 187
#define IDD_BROADCAST_PARAMETERS_DLG    188
#define IDI_LIVE_ICON                   190
#define IDI_OCCMUSIC_ICON               191
#define IDI_STNMUSIC_ICON               192
#define IDI_DVA_ICON                    193
#define IDI_PLAY_ICON                   194
#define IDI_STOP_ICON                   195
#define IDD_STATION_STATUS              196
#define IDD_STATION_DVA_STATUS          196
#define IDD_STATION_BROADCAST_DVA_STATUS 196
#define IDD_DIALOGNAMEWARNING           199
#define IDD_STATION_BROADCAST_LIVE_STATUS 200
#define IDD_DIALOGENTERSAVENAME         203
#define IDI_MUSICOFF_ICON               212
#define IDD_ADHOC_RECORD                213
#define IDI_ICON1                       217
#define IDD_DIALOG2                     219
#define IDD_DIALOGOVERWRITING_BROADCAST 219
#define IDI_AHR_RECORD                  220
#define IDI_AHR_DELETE                  222
#define IDI_DEPOTMUSIC_ICON             223
#define IDB_SPLASH                      226
#define IDC_VD_ED_CAMERA                1000
#define IDC_TAB1                        1000
#define IDC_MAIN_TAB                    1000
#define IDC_TrainId                     1000
#define IDC_TC_ED_TRAINID               1000
#define IDC_DV_CONTROLLER_CLOSE         1001
#define IDDISPLAY                       1001
#define IDC_TAB2                        1001
#define IDC_VD_CONTROLLER_CLOSE         1001
#define IDC_EDIT1                       1001
#define IDEXIT                          1002
#define IDC_EDIT2                       1002
#define IDC_LIST                        1003
#define IDC_TRAIN_LIST                  1003
#define IDC_VD_ED_TRAIN                 1004
#define IDC_EMERGENCY_PREDEFINED        1004
#define IDC_TakeControl                 1004
#define IDC_VD_RA_ASSIGN                1005
#define IDC_NORMAL_PREDEFINED           1005
#define IDC_LIST1                       1005
#define IDC_OUTERBOUND                  1005
#define IDC_STN_ZONE_SELECTION_LST      1005
#define IDC_Close                       1005
#define IDC_VD_RA_CLEAR                 1006
#define IDC_LIST2                       1006
#define IDC_INNERBOUND                  1006
#define IDC_SCHEDULE_LIBRARY            1006
#define IDC_STN_NORMAL_MESSAGES_LST     1006
#define IDC_STATION_SELECTED_MESSAGES_LST 1006
#define IDC_DVA_HEADER_LST_2            1006
#define IDC_STN_EMERGENCY_MESSAGES_LST  1007
#define IDC_STN_ZONE_SELECTION_LST2     1007
#define IDC_TB_TRAINBORNE               1008
#define IDC_ALL_OUTERBOUND              1008
#define IDC_STN_ADHOC_MESSAGES_LST      1008
#define IDC_BU_APPLY                    1009
#define IDC_ALL_INNERBOUND              1009
#define IDC_STN_NORMAL_MESSAGES_LST2    1009
#define IDC_STN_SELECTED_MESSAGES_LST   1009
#define IDC_BU_HELP                     1010
#define IDC_ALL_TRAINS                  1010
#define IDC_BU_APPLY2                   1011
#define IDC_BU_CLOSE                    1011
#define IDC_CLEAR_SELECTION             1011
#define IDC_EDIT3                       1011
#define IDC_REFRESH                     1012
#define IDC_ALL_REFRESH                 1012
#define IDC_CAR1_PID1                   1013
#define IDC_STATION_DISPLAY_TAB         1014
#define IDC_STATIC_BB					1014
#define IDC_VD_LT_MONITOR               1015
#define IDC_CAR1_PID2                   1015
#define IDC_STATIC_XB                   1015
#define IDC_CAR1_PID3                   1016
#define IDC_CAR1_PID4                   1017
#define IDC_CAR2_PID1                   1018
#define IDC_CAR2_PID2                   1019
#define IDC_CAR2_PID3                   1020
#define IDC_CAR2_PID4                   1021
#define IDC_CAR3_PID1                   1022
#define IDC_CAR3_PID2                   1023
#define IDC_CAR3_PID3                   1024
#define IDC_CAR3_PID4                   1025
#define IDC_TRAIN_DISPLAY_TAB           1026
#define IDC_TRAIN_SELECTION             1027
#define IDC_TRAIN_DOWNLOAD_TAB          1030
#define IDC_MESSAGE_SELECTION           1033
#define IDC_FREE_TEXT                   1035
#define IDC_EDIT_FREE_TEXT              1036
#define IDC_ADD_ENTRY                   1037
#define IDC_SPIN1                       1039
#define IDC_END_HOUR_ADJUST             1040
#define IDC_REPEAT_INTERVAL_ADJUST      1042
#define IDC_ISCS_CURRENT_VERSION        1043
#define IDC_DISPLAY_TIME_ADJUST         1043
#define IDC_SPIN5                       1044
#define IDC_START_HOUR                  1044
#define IDC_PID_GROUPLIST               1044
#define IDC_SPIN7                       1045
#define IDC_CONFIGURE_GROUPS            1045
#define IDC_START_MINUTE                1046
#define IDC_LED_FONT_TYPE               1048
#define IDC_ALL_CAR1                    1048
#define IDC_PID_ATTRIBUTES              1049
#define IDC_ALL_CAR2                    1049
#define IDC_SPIN2                       1050
#define IDC_ALL_CAR3                    1050
#define IDC_END_MINUTE_ADJUST           1050
#define IDC_SCH_END_HOUR                1051
#define IDC_ENTIRE_TRAIN                1051
#define IDC_DISPLAY_MINUTE_ADJUST       1051
#define IDC_SPIN6                       1052
#define IDC_CLEAR_PID_SELECTION         1052
#define IDC_EDIT4                       1053
#define IDC_SCROLL_SPEED                1054
#define IDC_SPIN3                       1058
#define IDC_INTENSITY2                  1058
#define IDC_DISPLAY_HOUR                1059
#define IDC_FONT_TYPE                   1060
#define IDC_SPIN8                       1060
#define IDC_DISPLAY_MINUTE              1061
#define IDC_SPIN9                       1064
#define IDC_END_MINUTE                  1065
#define IDC_END_HOUR                    1066
#define IDC_SCH_REMOVE_ENTRY            1067
#define IDC_SCH_SAVE                    1068
#define IDC_DISPLAY_TIME_MINUTE         1068
#define IDC_SCH_REMOVE_ALL_ENTRIES      1069
#define IDC_SCHEDULE_NAME               1070
#define IDC_SCH_NAME                    1071
#define IDC_DOWNLOAD_CURRENT            1072
#define IDC_UPGRADE                     1073
#define IDC_RETRY                       1074
#define IDC_RADIO_EMERGENCY             1076
#define IDC_SET_CURRENT_SCHEDULE        1076
#define IDC_SCHEDULE_LIST               1077
#define IDC_SCROLLBAR1                  1079
#define IDC_INTERVAL                    1080
#define IDC_SCH_PRIORITY                1081
#define IDC_TB_TRAINBORNE_GUI           1082
#define IDC_SCH_START_HOUR              1082
#define IDC_SCHEDULE_START_MINUTE       1083
#define IDC_SCH_END_MINUTE              1084
#define IDC_SCH_PREDEFINED_LIST         1085
#define IDC_SCHEDULE                    1086
#define IDC_TRAIN_INTENSITY             1087
#define IDC_PRIORITY                    1088
#define IDC_REPEAT_INTERVAL             1089
#define IDC_SPELL_CHECK                 1090
#define IDC_DISPLAY_TIME                1091
#define IDC_STATION_FREE_TEXT           1092
#define IDC_LIBRARY_VERSION_LIST        1093
#define IDC_VERSION_PROGRESS            1094
#define IDC_DOWNLOAD_STATUS             1095
#define IDC_TRAIN_VERSION_LIST          1096
#define ID_DISPLAY                      1097
#define IDC_LED_FONT_SIZE               1098
#define IDC_LED_FOREGROUND_COLOUR       1099
#define IDC_LED_BACKGROUND_COLOUR       1100
#define IDC_LED_BACKGROUND_COLOUR2      1101
#define IDC_LED_INTENSITY               1102
#define IDC_PLASMA_FOREGROUND_COLOUR    1103
#define IDC_LED_PLASMA_BACKGROUND_COLOUR 1104
#define IDC_PLASMA_BACKGROUND_COLOUR    1104
#define IDC_PREDEFINED_CONTENT          1105
#define IDC_PLASMA_FONT_TYPE            1105
#define IDC_PLASMA_FONT_SIZE            1106
#define IDC_START_HOUR_ADJUST           1108
#define IDC_START_MINUTE_ADJUST         1109
#define IDC_TRAIN_NORMAL_PREDEFINED     1111
#define IDC_TRAIN_EMERGENCY_PREDEFINED  1112
#define IDC_TRAIN_PREDEFINED_CONTENT    1113
#define IDC_MESSAGE_CONTENT             1114
#define IDC_ED_TRAINID                  1116
#define IDC_CAR1PID1                    1116
#define IDC_CH_COM                      1117
#define IDC_RADIO_PREDEFINED            1117
#define IDC_ED_COM_LOCATION             1118
#define IDC_RADIO_FREE_TEXT             1118
#define IDC_ED_TSI0                     1119
#define IDC_CAR1PID2                    1119
#define IDC_EMERGENCY_LABEL             1119
#define IDC_ED_TSI1                     1120
#define IDC_CAR1PID3                    1120
#define IDC_NORMAL_LABEL                1120
#define IDC_CH_ATS                      1121
#define IDC_CAR1PID4                    1121
#define IDC_CONTENT_LABEL               1121
#define IDC_ED_CUR_LOCATION             1122
#define IDC_CAR2PID1                    1122
#define IDC_LABEL1                      1122
#define IDC_ED_CCTVZONE                 1123
#define IDC_CAR2PID2                    1123
#define IDC_LABEL2                      1123
#define IDC_ED_SERVICE_NUMBER           1124
#define IDC_CAR2PID3                    1124
#define IDC_BU_SET                      1125
#define IDC_CAR2PID4                    1125
#define IDC_CH_MUTE                     1126
#define IDC_CAR3PID1                    1126
#define IDC_LABEL5                      1126
#define IDC_ED_TRACK                    1127
#define IDC_CAR3PID2                    1127
#define IDC_CH_LOCATION                 1128
#define IDC_CAR3PID3                    1128
#define IDC_CAR3PID4                    1129
#define IDC_LABEL8                      1129
#define IDC_LABEL9                      1130
#define IDC_LABEL10                     1131
#define IDC_LABEL11                     1132
#define IDC_LABEL12                     1133
#define IDC_LABEL13                     1134
#define IDC_LABEL14                     1135
#define IDC_LABEL15                     1136
#define IDC_LABEL16                     1137
#define IDC_LABEL17                     1138
#define IDC_LABEL18                     1139
#define IDC_LABEL19                     1140
#define IDC_LABEL20                     1141
#define IDC_LABEL21                     1142
#define IDC_LABEL22                     1143
#define IDC_LOCK                        1144
#define IDC_RADIO_CONTINUOUS            1146
#define IDC_RADIO_TIMED                 1147
#define IDC_NAME                        1148
#define IDC_CONTENT                     1149
#define IDC_START_TIME                  1152
#define IDC_END_TIME                    1153
#define IDC_EDIT_SCHEDULE               1158
#define IDC_NEW_SCHEDULE                1159
#define IDC_DELETE_SCHEDULE             1160
#define IDC_DOWNLOAD_STATUS_LIST        1162
#define IDC_FRAME1                      1163
#define IDC_STN_CHIME_CB                1164
#define IDC_STN_OCCMUSIC_BTN2           1165
#define IDC_STN_OCCMUSIC_BTN            1165
#define IDC_STN_MUSIC_BTN               1165
#define IDC_STN_STNMUSIC_BTN2           1166
#define IDC_STN_STNMUSIC_BTN            1166
#define IDC_OCC_MUSIC_BTN               1166
#define IDC_STN_LIVE_BTN                1167
#define IDC_STN_DVA_BTN                 1168
#define IDC_NORMAL_FILTER_TB            1169
#define IDC_EMERGENCY_FILTER_TB         1170
#define IDC_STN_EMERGENCY_FILTER_TB     1170
#define IDC_STN_CYCLIC_CB               1171
#define IDC_STN_MULTI_CB                1172
#define IDC_STN_RENAME_BTN              1173
#define IDC_STN_RECORD_BTN              1174
#define IDC_STN_PLAY_BTN                1175
#define IDC_STN_STOP_BTN                1176
#define IDC_BUTTON3                     1177
#define IDC_STN_CLEAR_BTN               1177
#define IDC_STN_CLEAR_ALL_BTN           1177
#define IDC_STN_STIS_CB                 1178
#define IDC_STN_SAVE_BTN                1179
#define IDC_STN_DELETE_BTN              1180
#define IDC_STN_CLEAR_ONE_BTN           1181
#define IDC_TIME_TB                     1184
#define IDC_NUMBER_TB                   1184
#define IDC_STN_INTERVAL_DTP            1203
#define IDC_TRN_CHIME_CB                1208
#define IDC_BUTTON1                     1209
#define IDC_KILL_ALL_GOING_DVA          1209
#define IDC_BUTTON2                     1210
#define IDC_LISTEN                      1210
#define IDC_BUTTONALLTRAINS             1211
#define IDC_BUTTON4                     1211
#define IDC_START                       1211
#define IDC_BUTTONCLEARALL              1212
#define IDC_BUTTON5                     1212
#define IDC_DELETE                      1212
#define IDC_BUTTONALLINBOUND            1213
#define IDC_BUTTON6                     1213
#define IDC_HELP_BTN                    1213
#define IDC_HELP_BTN2                   1213
#define IDC_STOP                        1213
#define IDC_BUTTONALLOUTBOUND           1214
#define IDC_EXECUTE_BTN                 1214
#define IDC_EXECUTE_BTN2                1214
#define IDC_BUTTONALLINBOUND2           1215
#define IDC_CLOSE_BTN                   1215
#define IDC_CLOSE_BTN2                  1215
#define IDC_BUTTONALLTRAINS2            1216
#define IDC_KILL_STATUS_BTN2            1216
#define IDC_BUTTONALLOUTBOUND2          1217
#define IDC_KILL_ALL_STATUS_BTN2        1217
#define IDC_BUTTONCLEARALL2             1218
#define IDC_RESTORE_STATUS_BTN2         1218
#define IDC_STATUS_CB2                  1219
#define IDC_ABOUTBUTTON                 1220
#define IDC_TABMARKER2                  1222
#define IDC_TABMARKER                   1222
#define IDC_STN_NORMAL_FILTER_TB        1225
#define IDC_TRN_START_DTP               1227
#define IDC_TRN_STOP_DTP                1228
#define IDC_TRN_MESSAGE_LST             1229
#define IDC_STN_ZONE_GROUP_COMBO        1234
#define IDC_STN_STATUS_PROGRESS         1236
#define IDC_STN_STATUS_PROGRESS_LST     1236
#define IDC_STN_STATUS_FAILURES         1237
#define IDC_STN_STATUS_FAILURES_LST     1237
#define ID_STN_STATUS_CLOSE_TRACK       1238
#define ID_STN_STATUS_CLOSE_TRACK_BTN   1238
#define ID_STN_STATUS_CLOSE             1239
#define ID_STN_STATUS_CLOSE_BTN         1239
#define ID_STN_STATUS_ABORT             1240
#define ID_STN_STATUS_ABORT_BTN         1240
#define ID_STN_STATUS_RETRY_ALL         1241
#define ID_STN_STATUS_RETRY_ALL_BTN     1241
#define ID_STN_STATUS_RETRY_FAILURES_BTN 1242
#define IDC_STATION_STATUS_MESSAGES_TB  1243
#define ID_STN_HELP                     1243
#define IDC_STATION_STATUS_BROADCAST_ID_TB 1244
#define IDC_STATION_STATUS_MODE_TB      1245
#define IDC_STATION_STATUS_BROADCAST_ID_TB_NEW 1245
#define IDC_STATION_STATUS_CHIME_TB     1246
#define IDC_STATION_STATUS_PRIORITY_TB  1247
#define IDC_STATION_STATUS_DWELL_TB     1248
#define IDC_STATION_STATUS_PERIOD_TB    1249
#define IDC_STATION_STATUS_START_TB     1250
#define IDC_STATION_STATUS_STOP_TB      1251
#define IDC_STN_CYCLICAL_START_HOUR     1255
#define IDC_STN_CYCLICAL_START          1255
#define IDC_STN_CYCLICAL_START_MIN      1256
#define IDC_STN_CYCLICAL_START_SEC      1257
#define IDC_STN_CYCLICAL_STOP_HOUR      1258
#define IDC_STN_CYCLICAL_STOP           1258
#define IDC_STN_CYCLICAL_STOP_MIN       1259
#define IDC_STN_CYCLICAL_STOP_SEC       1260
#define IDC_CYCLICAL_START_DATE         1261
#define IDC_STN_CYCLICAL_INTERVAL_MIN   1262
#define IDC_STN_CYCLICAL_INTERVAL       1262
#define IDC_STN_CYCLICAL_INTERVAL_SEC   1263
#define IDC_STN_CYCLICAL_DWELL_MIN      1264
#define IDC_STN_MB_DWELL_SEC            1264
#define IDC_STN_CYCLICAL_DWELL_SEC      1265
#define IDC_CYCLICAL_STOP_DATE          1265
#define IDC_STN_INBOUND_SELECTION_LST   1266
#define IDC_STN_OUTBOUND_SELECTION_LST  1267
#define IDC_TRN_SELECTED_MESSAGES_LST   1268
#define IDC_TRAIN_STATUS_PERIOD_TB      1271
#define IDC_EDITNAME                    1284
#define IDC_MAINTAB                     1285
#define IDC_STATICTEXT                  1288
#define IDC_EDIT_DESCRIPTION            1289
#define IDC_CHECK_TYPE                  1290
#define IDC_EDIT_TIME                   1291
#define IDC_RECORD_STATUS               1293
#define ID_CANCEL_CHANGES               1294
#define ID_CLOSE                        1295
#define IDC_MAINTEXT                    1296
#define IDC_STN_CYCLICAL_START_TIME     1299
#define IDC_STN_CYCLICAL_STOP_TIME      1300
#define IDC_ISCS_VERSION_FIELD          1301
#define IDC_STIS_TEXT                   1303
#define IDC_STN_STIS_CB_TEXT2           1304
#define IDC_STN_STIS_CB_TEXT1           1305
#define IDC_STATUS_TEXT                 1306
#define IDC_STATIC_DVA_LABEL            1307
#define IDD_VIDEODISPLAYMANAGER_DIALOG  2000
#define IDB_DV_OCC_OVERALL              2001
#define IDB_VD_OCC_OVERALL              2001
#define IDB_DV_OCC_OVERALL_H            2002
#define IDB_VD_OCC_OVERALL_H            2002
#define IDB_DV_OCC_WALL                 2003
#define IDB_VD_OCC_WALL                 2003
#define IDB_DV_OCC_WALL_H               2004
#define IDB_VD_OCC_WALL_H               2004
#define IDB_DV_OCC_CONSOLE              2005
#define IDB_VD_OCC_CONSOLE              2005
#define IDB_DV_OCC_CONSOLE_H            2006
#define IDB_VD_OCC_CONSOLE_H            2006
#define IDC_TAB_DVA_VERSIONS            2007
#define IDC_EDIT_VERSION_FIELD          2008
#define IDC_DVA_HEADER_LST              2009
#define IDC_DVA_VERSION_MAIN            2010
#define IDC_DVA_HELP                    2011
#define IDC_DVA_CLOSE                   2012
#define IDC_VD_MAP_QUAD1                2031
#define IDC_VD_MAP_QUAD2                2032
#define IDC_VD_MAP_QUAD3                2033
#define IDC_VD_MAP_QUAD4                2034
#define IDC_VD_TEXT_QUAD1               2038
#define IDC_VD_QUAD                     2038
#define IDC_VD_TEXT_QUAD2               2039
#define IDC_VD_TEXT_QUAD3               2040
#define IDC_VD_TEXT_QUAD4               2041
#define IDC_ST                          2067
#define IDD_TRAINBORNEMANAGER_COMMS_DIALOG 4051
#define IDD_TRAIN_DVA_VERSIONS          4052
#define ID_SHOWDETAILS_CLEARMONITOR     32771
#define ID_FILE_EXIT                    32771
#define ID_TRAINCONTROLLER_SHOWDETAILS  32772
#define IDC_DOWNLOAD_NEXT               4054
#define IDC_UPGRADE_NEXT                4055
#define IDC_UPGRADE_ISCS                4056
#define IDC_CANCEL_DOWNLOAD             4059
#define IDC_CLEAR_COMPLETED             4060
#define IDC_STATIC_PER_RUN_LABEL        4060
#define IDC_ISCS_NEXT_VERSION           4062
#define IDC_STATION_TRAIN_TAB           4063
#define IDC_STATION_LIBRARY_VERSION_LIST        4064
#define IDC_TRAIN_LIBRARY_VERSION_LIST          4066
#define IDC_HELP                        4065
#define IDC_CLOSE                       4067
#define IDC_SELECT_ALL_TRAINS           4068
#define IDC_DESELECT_ALL_TRAINS         4069
#define IDC_TRAIN_LIBRARY_DOWNLOAD_HELP 4070
#define IDC_TRAIN_LIBRARY_DOWNLOAD_CLOSE 4071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
