#pragma once
#pragma warning(disable: 4996 4819 4503 4172)
#include <ace/Future.h>
#include <ace/Singleton.h>
#include <ace/Process.h>
#include <ace/Process_Manager.h>
#include <boost/lexical_cast.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/regex.hpp>
#include <boost/filesystem.hpp>
#include <boost/tokenizer.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/foreach.hpp>
#include <boost/assign.hpp>
#include <boost/preprocessor.hpp>
#include <boost/bind.hpp>
#include <boost/function.hpp>
#include <boost/thread.hpp>
#include <boost/any.hpp>
#include <boost/utility.hpp>
#include <boost/type_traits.hpp>
#include <boost/format.hpp>
#include <boost/function_types/result_type.hpp>
#include <boost/signals2.hpp>
#include <boost/tuple/tuple.hpp>
#include <boost/tuple/tuple_comparison.hpp>
#include <boost/tuple/tuple_io.hpp>
#include <boost/container/map.hpp>
#include <boost/container/vector.hpp>
#include <boost/container/list.hpp>
#include <boost/move/move.hpp>
#include <boost/algorithm/cxx11/one_of.hpp>
#include <boost/algorithm/cxx11/none_of.hpp>
#include <boost/random/mersenne_twister.hpp>
#include <boost/random/uniform_int_distribution.hpp>
#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <set>
#include <algorithm>
#include <list>
#include <fstream>
#include <ctime>
