# The source code in this file is the property of
# Ripple Systems and is not for redistribution
# in any form.
#
# Source:   $File: //depot/PRIV_3001/TA_BASE/transactive/bus/generic_server_simulator/examples/echo_server/Makefile $
# @author:  Ripple
# @version: $Revision: #1 $
#
# Last modification: $DateTime: 2018/03/14 13:51:20 $
# Last modified by:  $Author: lim.cy $
#
# This file builds the EchoServerExample library
PROJ_ROOT_DIR = ../../../..
PROJ_NAME	= EchoServerExample
PROJ_SOURCE	= EchoCommsObserver.cpp \
		EchoModuleCreator.cpp \
		EchoSimulationModule.cpp

PROJ_TYPE	= lib
PROJ_OBJDIR	= ./obj
PROJ_INCDIR	= ./src \
		$(PROJ_ROOT_DIR)

##############################################################
# The main include file that has all the wiz bang stuff for neato compiling
##############################################################
include $(PROJ_ROOT_DIR)/tools/build/CommonMakefile.mak


install:
	#Do Nothing

