//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RadioSearchPage.rc
//
#define IDC_LINEFORWARD                 3
#define ID_HELPBUTTON                   4
#define IDC_FREECALL                    5
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RADIO_MANAGER_DIALOG        102
#define IDS_PROPSHT_CAPTION             103
#define IDD_CALLSTACK_CURRENT           105
#define IDS_PROPSHT_CAPTION1            106
#define IDD_CALLSTACK_OTHER             108
#define IDD_CALLSTACK_HISTORY           110
#define IDD_DYNAMIC_GROUP               112
#define IDD_FACILITYLINES               113
#define IDD_FACILITYSEARCH              114
#define IDD_RADIO_FACILITYSEARCH        114
#define IDD_FACILITYCONFIG              115
#define IDR_MAINFRAME                   128
#define IDR_POPUP_MENU                  131
#define IDD_FREECALL                    132
#define IDD_RADIOFORWARD                134
#define IDD_CONFERENCECALL              135
#define IDD_SELECTTEXTMESSAGE           136
#define IDD_FREETEXT                    137
#define IDD_FACILITYLINESv2             138
#define IDD_FACILITYCONFIG1             140
#define IDD_TELEPHONESTACK              141
#define IDD_CONFIRM_HOTLINE_CALL        142
#define IDD_TAA_HMI                     143
#define IDD_FACILITYGROUPPATCH          143
#define IDB_BITMAP1                     144
#define IDR_MAINTOOLBAR                 148
#define IDB_STATE                       152
#define IDB_CALLICONS                   153
#define IDD_NEW_TEXT_MESSAGE            154
#define IDC_ACCEPT                      1007
#define IDC_HELPBUTTON                  1008
#define IDC_RELEASE                     1009
#define IDC_RECALL                      1010
#define IDC_HOLD                        1011
#define IDC_INCLUDE                     1012
#define IDC_KILL                        1013
#define IDC_LOCATIONEDIT                1014
#define IDC_IDEDIT                      1015
#define IDC_TETRAIDEDIT                 1016
#define IDC_SUBIDEDIT                   1017
#define IDC_SUBTETRAIDEDIT              1018
#define IDC_SUBLOCATIONEDIT             1019
#define IDC_TEXTMESSAGE                 1020
#define IDC_SUBLOCATIONEDIT2            1021
#define IDC_CALLTYPE                    1022
#define IDC_EMERGENCYMODE               1023
#define IDC_CALL                        1024
#define IDC_CALLLIST                    1025
#define IDC_SEND_TEXT                   1025
#define IDC_REMOVE                      1026
#define IDC_EDIT_TEXT                   1026
#define IDC_CALLLIST2                   1027
#define IDC_SUBLOCATIONEDIT3            1028
#define IDC_RESET                       1029
#define IDC_CALLLIST3                   1030
#define IDC_CALL2                       1031
#define IDC_ADD                         1032
#define IDC_CALL3                       1033
#define IDC_SAVETRAINSELECTION          1033
#define IDC_GROUPLIST                   1034
#define IDC_CALL4                       1035
#define IDC_DELETETRAINSELECTION2       1035
#define IDC_TRAINLIST                   1036
#define IDC_OTHERCALLLIST               1037
#define IDC_TRAINLIST2                  1037
#define IDC_CALL5                       1038
#define IDC_ALL_INBOUND                 1038
#define IDC_HISTORYCALLLIST             1039
#define IDC_ALL_OUTBOUND                1039
#define IDC_CALL6                       1040
#define IDC_CLEAR_ALL                   1040
#define IDC_COMBO1                      1041
#define IDC_CALL7                       1042
#define IDC_ALL_TRAINS                  1042
#define IDC_COMBO2                      1043
#define IDC_CALL8                       1048
#define IDC_SUBLOCATIONEDIT4            1049
#define IDC_INITIATOR                   1050
#define IDC_SUBLOCATIONEDIT5            1051
#define IDC_SPEAKING                    1052
#define IDC_COMBO3                      1053
#define IDC_ID_COMBO                    1053
#define IDC_LIST1                       1054
#define IDC_BUTTON1                     1055
#define IDC_PATCHLIST                   1055
#define IDC_BUTTON2                     1056
#define IDC_MESSAGETEXT                 1057
#define IDC_FREETEXT                    1058
#define IDC_BUTTON4                     1059
#define IDC_MESSAGELIST                 1060
#define IDC_SELECTEDTEXT                1061
#define IDC_TREE1                       1062
#define IDC_EDIT1                       1063
#define IDC_SUBSCRIBERSEARCH            1064
#define IDC_EDIT2                       1065
#define IDC_BUTTON3                     1066
#define IDC_EDIT3                       1067
#define IDC_TAB1                        1068
#define IDC_CHECK1                      1069
#define IDC_CHECK2                      1070
#define IDC_CHECK3                      1071
#define IDC_CA_ID                       1100
#define IDC_CA_TETRAID                  1101
#define IDC_CA_LOCATION                 1102
#define IDC_RADIO_FACILITIES            1103
#define IDC_RADIO_CALL_STACK            1104
#define IDC_CALL_STACK_TAB              1105
#define IDC_RADIO_FACILITIES_TAB        1106
#define IDC_CALLLIST_OUT                1107
#define IDC_CALLLIST_HOLD               1107
#define IDC_CALLLIST_IN                 1108
#define ID_HOLDBUTTON                   1109
#define IDC_SETBUTTON                   1110
#define IDC_EDITLABEL                   1111
#define IDC_EDITTETRAID                 1112
#define IDC_SA_ID                       1200
#define IDC_SA_LOCATION                 1201
#define IDC_SA_TETRAID                  1202
#define IDC_HOT_BUTTON1                 2000
#define IDC_HOT_BUTTON2                 2001
#define IDC_HOT_BUTTON3                 2002
#define IDC_HOT_BUTTON4                 2003
#define IDC_HOT_BUTTON5                 2004
#define IDC_HOT_BUTTON6                 2005
#define IDC_HOT_BUTTON7                 2006
#define IDC_HOT_BUTTON8                 2007
#define IDC_DIRECT_LINE_BUTTON_1        2049
#define IDC_DIRECT_LINE_BUTTON_2        2050
#define IDC_DIRECT_LINE_BUTTON_3        2051
#define IDC_DIRECT_LINE_BUTTON_4        2052
#define IDC_DIRECT_LINE_BUTTON_5        2053
#define IDC_DIRECT_LINE_BUTTON_6        2054
#define IDC_DIRECT_LINE_BUTTON_7        2055
#define IDC_DIRECT_LINE_BUTTON_8        2056
#define IDC_DIRECT_LINE_BUTTON_9        2057
#define IDC_DIRECT_LINE_BUTTON_10       2058
#define IDC_DIRECT_LINE_BUTTON_11       2059
#define IDC_DIRECT_LINE_BUTTON_12       2060
#define IDC_DIRECT_LINE_BUTTON_13       2061
#define IDC_DIRECT_LINE_BUTTON_14       2062
#define IDC_DIRECT_LINE_BUTTON_15       2063
#define IDC_DIRECT_LINE_BUTTON_16       2064
#define IDC_DIRECT_LINE_BUTTON_17       2065
#define IDC_DIRECT_LINE_BUTTON_18       2066
#define IDC_DIRECT_LINE_BUTTON_19       2067
#define IDC_DIRECT_LINE_BUTTON_20       2068
#define IDC_DIRECT_LINE_BUTTON_21       2069
#define IDC_DIRECT_LINE_BUTTON_22       2070
#define IDC_DIRECT_LINE_BUTTON_23       2071
#define IDC_DIRECT_LINE_BUTTON_24       2072
#define IDC_DIRECT_LINE_BUTTON_25       2073
#define IDC_DIRECT_LINE_BUTTON_26       2074
#define IDC_DIRECT_LINE_BUTTON_27       2075
#define IDC_DIRECT_LINE_BUTTON_28       2076
#define IDC_DIRECT_LINE_BUTTON_29       2077
#define IDC_DIRECT_LINE_BUTTON_30       2078
#define IDC_DIRECT_LINE_BUTTON_31       2079
#define IDC_DIRECT_LINE_BUTTON_32       2080
#define IDC_DIRECT_LINE_BUTTON_33       2081
#define IDC_DIRECT_LINE_BUTTON_34       2082
#define IDC_DIRECT_LINE_BUTTON_35       2083
#define IDC_DIRECT_LINE_BUTTON_36       2084
#define IDC_RADIO_BUTTON_GROUP          2090
#define IDC_RADIO1                      2091
#define IDC_RADIO2                      2092
#define IDC_RADIO3                      2093
#define IDC_CURRENTCALLLIST             2100
#define IDC_PATCH                       2101
#define IDC_AUTOMATIC_CALL              2103
#define IDC_NEW_TEXT                    2104
#define IDC_DELETE_TEXT                 2105
#define ID_OK                           2105
#define IDC_UPDATE_TEXT                 2106
#define IDC_VOLUME_UP                   2106
#define IDC_VOLUME_DOWN                 2107
#define IDC_PTT_REQUIRED_TEXT           2108
#define IDC_PTT_TALKING_TEXT            2109
#define IDC_PTT_LISTENING_TEXT          2110
#define IDC_TSI_COMBO                   2111
#define IDC_PTT_TALKING_RECTANGLE       2112
#define IDC_PTT_LISTENING_RECTANGLE     2113
#define IDC_LOCATION_TAB                2115
#define IDC_DIRECTORY_BOX               2116
#define IDC_ADD_MONITOR                 2117
#define IDI_CALL_CONFERENCE             3000
#define IDI_CALL_DRIVER                 3001
#define IDI_CALL_VOICE                  3002
#define IDI_CALL_SDS                    3003
#define ID_LINE_FORWARD_MODE            32772
#define IDM_UPDATEBUTTONS               32773
#define IDM_LOADCALLS                   32774
#define ID_LINEFORWARD                  32775
#define ID_FREECALL                     32776
#define ID_BUTTON32777                  32777
#define ID_HELP_RADIOMANAGERHELP        32778
#define ID_HELP_ABOUTRADIOMANAGER       32779
#define ID_VIEW_STATUSBAR               32781
#define ID_BUTTON32782                  32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         2118
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
