/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/src/RadioEventSubscriber.h $
  * @author:  Ripple
  * @version: $Revision: #2 $
  *
  * Last modification: $DateTime: 2010/05/10 14:39:08 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//  RadioEventSubscriber.h
//  Implementation of the Class RadioEventSubscriber
//  Created on:      26-Nov-2003 03:40:30 PM
///////////////////////////////////////////////////////////

#if !defined(RadioEventSubscriber_INCLUDED_)
#define RadioEventSubscriber_INCLUDED_

#include "core/message/src/SpecialisedMessageSubscriber.h"
#include "core/message/IDL/src/CommsMessageCorbaDef.h"
#include "bus/security/security_utilities/src/SecurityUtilities.h"

/**
 * This class will listen for train messages generated by the radio agent and pass
 * them to the TrainManager for processing.
 */
namespace TA_IRS_App
{
	class RadioSessionServant;

	class RadioEventSubscriber : public TA_Base_Bus::ISessionUpdateObserver
	{
		public:
			RadioEventSubscriber(RadioSessionServant& radioSessionServant,unsigned long consoleID,unsigned long locationKey,
				TA_Base_Bus::SessionUpdateSubject& sessionUpdateSubject);
			virtual ~RadioEventSubscriber(){}
			void startSubscription();
			void stopSubscription();

		public:
			virtual void sessionBegin( const std::string& session, unsigned long user,
			                       unsigned long profile, unsigned long location,
								   unsigned long workstation );
			virtual void sessionEnd( const std::string& session );
	
		private:

			RadioEventSubscriber(const RadioEventSubscriber& theEventSubscriber);

			RadioSessionServant&    m_radioSessionServant;
			unsigned long           m_consoleID;
			unsigned long           m_locationKey;

            std::string m_session; // limin++ CL-21361
	
	};
};
#endif // !defined(RadioEventSubscriber_INCLUDED_)
