# The source code in this file is the property of
# Ripple Systems and is not for redistribution
# in any form.
#
# Source:  $File: //depot/PRIV_4669_TRAIN_ECP/CODE_4669/transactive/bus/trains/TrainCorbaProxy/Makefile $ 
# Author:  Ripple
# Version: $Revision: #1 $
#
# Last modification: $DateTime: 2008-1-21 17:24:30 $
# Last modified by:  $Author: buildteam $
#

PROJ_ROOT_DIR	= ../../../../..
PROJ_CODE_DIR	= transactive/bus/trains/TrainCommonLibrary
PROJ_NAME	= TA_TrainCommonLibrary

PROJ_SOURCE	= \
		AgentCommunicationException.cpp \
		AtsZoneUtils.cpp \
		BadCommandException.cpp \
		CallTypes.cpp \
		CctvConflictException.cpp \
		CctvException.cpp \
		CctvTypes.cpp \
		CommonTypes.cpp \
		GroupInUseException.cpp \
		InvalidParameterException.cpp \
		InvalidSelectionListException.cpp \
		InvalidTrainException.cpp \
		LocationCache.cpp \
		MpuChangeoverException.cpp \
		OperationNotSupportedException.cpp \
		PaException.cpp \
		PaTypes.cpp \
		PecException.cpp \
		PecTypes.cpp \
		ProtocolCallTypes.cpp \
		ProtocolCctvTypes.cpp \
		ProtocolCommonTypes.cpp \
		ProtocolException.cpp \
		ProtocolPaTypes.cpp \
		ProtocolPecTypes.cpp \
		ProtocolTtisTypes.cpp \
		RadioGroupTypes.cpp \
		RadioGroupUtils.cpp \
		StateUpdateTypes.cpp \
		TrainAccessDeniedException.cpp \
		TrainCallException.cpp \
		TrainException.cpp \
		TrainInformationTypes.cpp \
		TrainRadioException.cpp \
		TrainTimeoutException.cpp \
		TrainTimerException.cpp \
		TrainTransmissionFailureException.cpp \
		TransactionCancelledException.cpp \
		TtisException.cpp \
		TtisTypes.cpp

PROJ_TYPE	= lib
PROJ_INC_DIR    = ./src $(PROJ_ROOT_DIR)/code/transactive $(PROJ_ROOT_DIR)/sdk/include/transactive
PROJ_OUT_DIR    = $(PROJ_ROOT_DIR)/sdk/$(OPERATING_SYSTEM)_$(STRING_FLAG)$(RELEASE_FLAG)

##############################################################
# The main include file that has all the wiz bang stuff for neato compiling
##############################################################

include $(PROJ_ROOT_DIR)/code/tools/build/CommonMakefile.mak


install:
	#Do Nothing


