/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/PRIV_3001/3001/transactive/bus/radio/PTTMonitorLibrary/src/PTTButtonException.cpp $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2018/03/14 13:51:20 $
  * Last modified by:  $Author: lim.cy $
  *
  */

///////////////////////////////////////////////////////////
//
//  RadioMethodTimeoutException.cpp
//  Implementation of the Class RadioMethodTimeoutException
//  Generated by Enterprise Architect
//  Created on:      29-Oct-2003 17:47:05
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "PTTButtonException.h"


using namespace TA_IRS_Bus;

PTTButtonException::PTTButtonException(std::string error) //throw() : TA_Base_Core::TransactiveException(error)
{

}


PTTButtonException::~PTTButtonException() throw()
{

}


