//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by step_plugin.train_tis_step.rc
//
#define IDD_PLAN_STEP_EDIT_TRAIN_TIS_DLG 26350
#define IDD_PLAN_STEP_PARAMETER_TRAIN_TIS_MESSAGE_EDIT_DLG 26351
#define IDC_TRAINTIS_MESSAGE_EDIT       26361
#define IDC_TRAINTIS_PICK_MESSAGE_BUTTON 26362
#define IDC_TRAINTIS_PRIORITY_COMBO     26363
#define IDC_TRAINTIS_DURATION_PICKER    26364
#define IDC_TRAINTIS_TRAIN_ID_RADIO     26365
#define IDC_TRAINTIS_TRAIN_ID_COMBO     26366
#define IDC_TRAINTIS_INBOUND_TRAINS_RADIO 26367
#define IDC_TRAINTIS_OUTBOUND_TRAINS_RADIO 26368
#define IDC_TRAINTIS_ALL_TRAINS_RADIO   26369
#define IDS_TRAINTIS_STEP_PARAMETER_TRAIN 26371
#define IDS_TRAINTIS_STEP_PARAMETER_TIS_MESSAGE 26372
#define IDS_TRAINTIS_STEP_PARAMETER_TIS_PRIORITY 26373
#define IDS_TRAINTIS_STEP_PARAMETER_TIS_DURATION 26374
#define IDC_TRAINTIS_LIBRARY_TYPE     26375
#define IDC_TRAINTIS_DEST_LIBRARY_VERSION 26376
#define IDC_TRAINTIS_MSG_LIBRARY_VERSION 26377
#define IDC_TRAINTIS_MESSAGE_LIST     26378
#define IDC_TRAINTIS_PARAMETER_NAME   26479

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        27000
#define _APS_NEXT_COMMAND_VALUE         27001
#define _APS_NEXT_CONTROL_VALUE         27002
#define _APS_NEXT_SYMED_VALUE           27003
#endif
#endif
