//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by step_plugin.launch schematic_step.rc
//
#define IDD_PLAN_STEP_EDIT_LAUNCH_SCHEMATIC_DLG          26580
#define IDD_LAUNCH_SCHEMATIC_DLG                         26581
#define IDC_LAUNCH_SCHEMATIC_COMMAND_LINE_EDIT           26590
#define IDC_LAUNCH_SCHEMATIC_SCHEMATIC_NAME_COMBO        26591
#define IDC_LAUNCH_SCHEMATIC_SCREEN_NUMBER_EDIT          26592
#define IDC_LAUNCH_SCHEMATIC_SCREEN_NUMBER_SPIN          26593
#define IDC_LAUNCH_SCHEMATIC_SCREEN_NUMBER_COMBO         26594
#define IDC_LAUNCH_SCHEMATIC_ACTIVE_INSTANCE_EDIT        26595
#define IDC_LAUNCH_SCHEMATIC_PLAN_PATH_EDIT              26596
#define IDC_LAUNCH_SCHEMATIC_LOCATION_NAME_EDIT          26597
#define IDC_LAUNCH_SCHEMATIC_STEP_NUMBER_EDIT            26598

#define IDS_LAUNCH_SCHEMATIC_REPORT_COMPLETION_STATUS    26600
#define IDS_LAUNCH_SCHEMATIC_STEP_PARAMETER_SCHEMATIC    26601
#define IDS_LAUNCH_SCHEMATIC_STEP_PARAMETER_COMMAND_LINE 26602
#define IDS_LAUNCH_SCHEMATIC_STEP_PARAMETER_SCREEN       26603
#define IDS_LOAD_SCHEMATICS                              26604
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        27000
#define _APS_NEXT_COMMAND_VALUE         27001
#define _APS_NEXT_CONTROL_VALUE         27002
#define _APS_NEXT_SYMED_VALUE           27003
#endif
#endif
