# The source code in this file is the property of
# Ripple Systems and is not for redistribution
# in any form.
#
# Source:   $File: //depot/3001_TIP_NEW/TA_BASE/transactive/bus/generic_server_simulator/examples/echo_server/Makefile $
# @author:  Ripple
# @version: $Revision: #2 $
#
# Last modification: $DateTime: 2012/02/06 16:15:14 $
# Last modified by:  $Author: haijun.li $
#
# This file builds the EchoServerExample library
PROJ_ROOT_DIR = ../../../..
PROJ_NAME	= EchoServerExample
PROJ_SOURCE	= EchoCommsObserver.cpp \
		EchoModuleCreator.cpp \
		EchoSimulationModule.cpp

PROJ_TYPE	= lib
PROJ_OBJDIR	= ./obj
PROJ_INCDIR	= ./src \
		$(PROJ_ROOT_DIR)

##############################################################
# The main include file that has all the wiz bang stuff for neato compiling
##############################################################
include $(PROJ_ROOT_DIR)/tools/build/CommonMakefile.mak


install:
	#Do Nothing

