//
// The source code in this file is the property of
// Ripple Systems and is not for redistribution
// in any form.
//
// Source:   $File: //depot/PRIV_3001/3001/transactive/bus/ats/ats_agent/IDL/src/IAtsCorbaDef.idl $
// @author:  Darren Sampson
// @version: $Revision: #1 $
//
// Last modification: $DateTime: 2018/03/14 13:51:20 $
// Last modified by:  $Author: lim.cy $
//
// ATS IDL interface.
//
// This IDL is used to aggregate all the IDL to be implemented by the ATS agent.
// This should not be used by clients and will be moved to the AtsAgent directory 
// when the include paths for the IDL compiler are sorted out.
//
#include "bus/ats/ats_agent/IDL/src/IAtsEcsCorbaDef.idl"
#include "bus/ats/ats_agent/IDL/src/IAtsWildCorbaDef.idl"
#include "bus/ats/ats_agent/IDL/src/IAtsTrainCorbaDef.idl"
#include "bus/ats/ats_agent/IDL/src/IAtsPasCorbaDef.idl"
#include "bus/ats/ats_agent/IDL/src/IAtsTisCorbaDef.idl"
#include "bus/ats/ats_agent/IDL/src/IAtsCctvCorbaDef.idl"
#include "bus/ats/ats_agent/IDL/src/IAtsPsdCorbaDef.idl"

module TA_IRS_Bus
{

	interface IAtsCorbaDef : IAtsEcsCorbaDef,
	                         IAtsWildCorbaDef,
	                         IAtsTrainCorbaDef,
	                         IAtsPasCorbaDef,
	                         IAtsTisCorbaDef,
							 IAtsCctvCorbaDef,
							 IAtsPsdCorbaDef
	{

	}; // IAtsCorbaDef
}; // TA_Bus
