/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/PRIV_3001/3001/transactive/app/ecs/ECSAgent/src/BooleanContext.h $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2018/03/14 13:51:20 $
  * Last modified by:  $Author: lim.cy $
  *
  */
///////////////////////////////////////////////////////////
//
//  BooleanContext.h
//  Implementation of the Class BooleanContext
//  Generated by Enterprise Architect
//  Created on:      25-Sep-2003 18:53:34
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(BooleanContext__INCLUDED_)
#define BooleanContext__INCLUDED_




class BooleanContext
{

public:
    BooleanContext();

    virtual ~BooleanContext();

    void setControl();

    void setMonitor();


protected:

    volatile bool           m_isEnabled;


private:
    BooleanContext( const BooleanContext& theBooleanContext);

};

#endif // !defined(BooleanContext__INCLUDED_)
