/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/RadioProtocolLibrary/src/DisconnectEventReader.cpp $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2008/11/28 16:26:01 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//
//  DisconnectEventReader.cpp
//  Implementation of the Class DisconnectEventReader
//  Generated by Enterprise Architect
//  Created on:      10-Nov-2003 16:38:14
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "DisconnectEventReader.h"
#include "core/utilities/src/TAAssert.h"

namespace TA_IRS_App
{
	const unsigned int DisconnectEventReader::DISCONNECT_REFERENCE_EVENT_LENGTH =  36;
    const unsigned int DisconnectEventReader::CALL_REFERENCE_START              =  0;
    const unsigned int DisconnectEventReader::REASON_START                      =  4;


    DisconnectEventReader::DisconnectEventReader(RadioEvent& event)
		   : RadioEventReader(event,EVENT_DISCONNECT,DISCONNECT_REFERENCE_EVENT_LENGTH)
    {
    }

    DisconnectEventReader::~DisconnectEventReader()
    {
    }


    const DisconnectEventReader::RadioReference DisconnectEventReader::getCallReference() const
    {
	    return getParameterLong(CALL_REFERENCE_START);
    }

    const std::string DisconnectEventReader::getReason() const
    {
		return getParameterShortString(REASON_START);
    }
     

}


