/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/RadioProtocolLibrary/src/RadioMethodDisconnect.h $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2008/11/28 16:26:01 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//
//  RadioMethodDisconnect.h
//  Implementation of the Class RadioMethodDisconnect
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2003 11:59:15
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(RadioMethodDisconnect_DF40F825_9087_4f9a_9DF3_584393212425__INCLUDED_)
#define RadioMethodDisconnect_DF40F825_9087_4f9a_9DF3_584393212425__INCLUDED_

#include "RadioMethodCallReference.h"
/**
* Disconnect a specified call
* @version 1.0
* @generator Enterprise Architect
* @created 15-Nov-2003 11:59:15
*/

namespace TA_IRS_App
{
	class RadioMethodDisconnect : public RadioMethodCallReference
	{

		public:
			/**
			* Constructor
			* @param    sessionRef
			* @param    callRef
			*/
			RadioMethodDisconnect(RadioSessionReference sessionRef, RadioCallReference callRef);
			virtual ~RadioMethodDisconnect();

		public:
	};
}; // Namespace

#endif // !defined(RadioMethodDisconnect_DF40F825_9087_4f9a_9DF3_584393212425__INCLUDED_)
