/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/RadioProtocolLibrary/src/SelectEventReader.cpp $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2008/11/28 16:26:01 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//
//  SelectEventReader.cpp
//  Implementation of the Class DeleteReferenceEventReader
//  Generated by Enterprise Architect
//  Created on:      10-Nov-2003 16:38:14
//  Original author: Andy Parker
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "SelectEventReader.h"
#include "core/utilities/src/TAAssert.h"

namespace TA_IRS_App
{

    const unsigned int SelectEventReader::SELECT_EVENT_LENGTH     =  4;
    const unsigned int SelectEventReader::SELECT_REFERENCE_START  =  0;


    SelectEventReader::SelectEventReader(RadioEvent& event)
						    : RadioEventReader(event,EVENT_SELECT,SELECT_EVENT_LENGTH)
    {
    }

    SelectEventReader::~SelectEventReader()
    {
    }


    const SelectEventReader::RadioReference SelectEventReader::getReference() const
    {
	    return getParameterLong(SELECT_REFERENCE_START);
    }

}


